### ISSUE TITLE
Expose Interfaces for Component Props

### ISSUE THREAD

**Issue by martinmckenna** [express-labs/pure-react-carousel#102]
It would be awesome if the interfaces were exported. I'd like to be able to extend the prop interfaces for some of the components, such as `<Dots />`.

Otherwise, I have to do this

```js
interface MyPropsWithDotProps {
  [key: string]: any;
  myNewProp: () => void;
}
```

**Comment by martinmckenna** [comment]
@mrbinky3000 gotcha. What I'm basically asking for it to prepend this line with `export`. It's a pretty common practice with most libraries because it gives developers to create enhanced versions of the components from a particular library.

Here's an example usage. Material-UI exposes it's props so that I can build on top with my own version of a `<FormControlLabel />`

```js
/** 
 * import both the FormControlLabel component and it's props from MUI 
 */
import _FormControlLabel, {
  FormControlLabelProps as _FormControlLabelProps
} from '@material-ui/core/FormControlLabel';

/** my props extend the MUI props */
export interface MyProps extends _FormControlLabelProps {
  helperText?: string; // my own prop
}

const FormControlLabel: React.StatelessComponent<MyProps> = props => {
  const { helperText, ...otherProps } = props;
  return (
    <div>
      <_FormControlLabel {...otherProps} />
      {helperText && (
        <p>{helperText}</p>
      )}
    </div>
  );
};

export default FormControlLabel
```

**Comment by mrbinky3000** [comment]
I'm fine with this.  Should we go ahead and add them to all the other similar lines too?

**Comment by martinmckenna** [comment]
Yeah that would be amazing

**Comment by tim-steele** [comment]
@martinmckenna Is this something you would be willing to create a PR for since you have more familiarity with TypeScript?

**Comment by martinmckenna** [comment]
@tim-steele yeah - I think it's important. I'll try to PR if I have time, but no promises

**Comment by martinmckenna** [comment]
@tim-steele @mrbinky3000 #121
