### ISSUE TITLE
Option to turn off dragging in the browser

### ISSUE THREAD

**Issue by martinmckenna** [express-labs/pure-react-carousel#103]
I'm getting really weird behavior where the slide will stick to the cursor after I stop holding down my mouse button. In the following screenshot, I am not holding down my mouse button when I move back and forth

![shrek2](https://user-images.githubusercontent.com/7387001/48143220-541fea80-e27c-11e8-8dbc-4e7b53b71831.gif)

I wish there was a way to turn off dragging the image with the mouse in the browser

**Comment by mrbinky3000** [comment]
There is!  :-)

![screen shot 2018-11-13 at 9 21 12 am](https://user-images.githubusercontent.com/161068/48419272-8373a300-e725-11e8-8a98-fde6fa3d07aa.png)

^ CarouselProvider component.
