### ISSUE TITLE
Allow space-between items / flexbox support?

### ISSUE THREAD

**Issue by fullstackzach** [express-labs/pure-react-carousel#109]
Hi, first off I think this library is great! It's nice to see a pure react solution for a carousel. 
I have a carousel of items that is displaying different amounts of items based on the viewport size (like 4 at a time for desktop, 3 or 2 for tablet and 1 for mobile). I am already keeping the slider to be a fixed height to stop the intrinsic ratio effect from happening.

I am trying to align the carousel items to be `space-between` so that the items are aligned flush with each end of the visible div, similar to how flexbox `justify-content` in flexbox works:

![image](https://user-images.githubusercontent.com/13011363/48634563-75bf5700-e98b-11e8-801f-c2cb800b3f96.png)

However, I haven't had any luck using flexbox to align these. 

Do you have any suggestions on how I could style to achieve this? Or, would consider adding this as an alignment option to `<Slider />`?

**Comment by mrbinky3000** [comment]
In your example, what happens if there is a slide 4?

**Comment by edshav** [comment]
@mrbinky3000  if there is a slide 4
![image](https://user-images.githubusercontent.com/31659942/122672708-b3d12700-d1d5-11eb-8e14-ec25fbeaa27c.png)
