### ISSUE TITLE
is there going to be support for babel7 soon?

### ISSUE THREAD

**Issue by piklas** [express-labs/pure-react-carousel#114]

**Comment by mrbinky3000** [comment]
Yes, we are most likely going to be updating our code to use babel 7 in the near future.  However, the code in pure-react-carousel's dist folder, the code that you are importing into your project, is already compiled.  You should  not be compiling it again.  Perhaps you need to configure your project to skip compiling node_modules?

**Comment by piklas** [comment]
Hi, the code is working fine most of the time, except in ie11 I get 
Error: Out of stack space 
It is triggering on Slide, ButtonBack and ButtonNext components.
and yes we are using the already compiled version, but if you look on babel 6 and babel 7 versions you will notice that there are some differences in how it compiles.

The use is straight forward from your tutorial, works good on every other browser but ie :
 <CarouselProvider
        naturalSlideWidth={100}
        naturalSlideHeight={125}
        totalSlides={3}
      >        
        <Slider>
          <Slide index={0}>I am the first Slide.</Slide>
          <Slide index={1}>I am the second Slide.</Slide>
          <Slide index={2}>I am the third Slide.</Slide>
        </Slider>
        <ButtonBack>Back</ButtonBack>
        <ButtonNext>Next</ButtonNext>
      </CarouselProvider>
Thanks

**Comment by piklas** [comment]
My issue got resolved!! This is a pure polyfill issue. 
We added 'core-js/fn/symbol/for' polyfill in webpack config 'entry' and it worked.
