### ISSUE TITLE
How to know when we reached the end / start of the carousel ?

### ISSUE THREAD

**Issue by arnaudambro** [express-labs/pure-react-carousel#117]
I want to hide the Back button when the carousel is at start, and the Next button when the carousel is at the end, how can I get the proper information ?
Thanks

**Comment by mrbinky3000** [comment]
The buttons are enabled and disabled automatically by PRC. The buttons have classes assigned to them that state when they are enabled, disabled.  Tie into the classes with your own css.   If you simple want to hide them, add some css to set display:none or visibility:hidden 

The specific classes added to each component are in the docs.

**Comment by arnaudambro** [comment]
Thanks @mrbinky3000 for your quick reply.
My bad, I didn't catch the 'disabled' attribute passed down to the button.
I did a simple `.carousel__back-button:disabled { visibility: hidden }` and everything is perfect.
Nice job, my favorite carousel until now !
