### ISSUE TITLE
Scroll chaining

### ISSUE THREAD

**Issue by DanielNoonan** [express-labs/pure-react-carousel#118]
I am using a vertically scrolling carousel with touchEnabled set to true. When trying to scroll the carousel (vertically) with an ios device the whole page is scrolling.

It work better on Android. I'm using chrome for each OS.

Is there a way of preventing vertical scroll chaining, so the carousel will scroll vertically without also scrolling the page?

**Comment by gundupatil1** [comment]
Facing the same issue here
