### ISSUE TITLE
Error importing module with webpack and source maps

### ISSUE THREAD

**Issue by dankraus** [express-labs/pure-react-carousel#119]
Hi there,

This library looks to be exactly what I need. Thorough docs! 

I'm presently having an issue importing the module in my webpack build. Seems like the sourceMap comment in `/dist/index.es.js` is the root cause and throws `Uncaught SyntaxError: Unexpected string` from the pure-react-carousel module in my bundle.

```
....
//# sourceMappingURL=index.es.js.map
```

Here's a snippet of my Webpack 4 config.
```
devtool: 'eval-source-map',
resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json']
},
module: {
    rules: [
        {
            test: /\.tsx?$/,
            loader: 'awesome-typescript-loader',
            exclude: /node_modules/
        },
        // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
        { enforce: 'pre', test: /\.js$/, loader: 'source-map-loader' },
        stylesheetRule,
        fileLoaderRule
    ]
},
```

Seems that if I remove `devtool: 'eval-source-map',` then things work fine with the library imported as packaged.

Any ideas or any other info I could provide?

**Comment by tim-steele** [comment]
@dankraus It looks like from your WebPack you are importing it as TypeScript, is that correct?

**Comment by dankraus** [comment]
> @dankraus It looks like from your WebPack you are importing it as TypeScript, is that correct?

Hi Tim - yeah we're using a typescript loader to process our `.ts` and `.tsx` files. We're looking to use pure-react-carousel from a `.tsx` component file.

If I manually remove the sourcemap comment in `/node_modules/pure-react-carousel/dist/index.es.js` things work as expected.

**Comment by tim-steele** [comment]
@dankraus I will review it. I have to admit, someone was kind enough to do the TypeScript implementation for us, as we don't use TypeScript. This seems like there is a conflict happening in WebPack or the TypeScript loader.

**Comment by dankraus** [comment]
Thanks @tim-steele - i'm not entirely sure it's TypeScript related, but it could be. It's all to do with the source map. When I have some time, i'll try and put a repo together to repro it and remove TypeScript out of it.
