### ISSUE TITLE
Dots in one line when not enough width

### ISSUE THREAD

**Issue by knitevision1** [express-labs/pure-react-carousel#123]
Hi and thanks for the component, it's really nice.

I needed to have thumbnails:
```js
{images.map((image, index) => (
    <Dot
        slide={index}
        key={`dot-${index}`}
    >
        <Image src={image.thumbnail} hasMasterSpinner={false} />
    </Dot>
))}
```

However, if there's not enough width/height - dots are split into multiple lines, while ideally they should be displayed in one line and transformed by `translate` (like main image sliding)

However since it's not covered in the docs, I'm a bit confused how to achieve that.

**Comment by tim-steele** [comment]
@knitevision1 Just to clarify - you are using images instead of "dots", and the size of the images is causing the images to wrap on multiple lines? 

Is it the width of the carousel that is causing the problem?

**Comment by tim-steele** [comment]
@knitevision1 I am closing this as it was released with version 1.19.0.

**Comment by tim-steele** [comment]
My mistake, this is still something we are waiting for your response on.

**Comment by mrbinky3000** [comment]
If I'm reading this correctly, I think he wants the dots to slide in their own tiny carousel beneath the main carousel.  Dots are for navigation.   He's putting images in his dots which is fine (we do that for our "thumbnail" effect)
