### ISSUE TITLE
Event listener for "after slide"

### ISSUE THREAD

**Issue by jamesmosier** [express-labs/pure-react-carousel#127]
Thanks for a great project! I was wondering if there were any exposed event handlers or "best practices" around listening for an "after slide" event? Normally I'd just hook into the next/prev buttons, but with the ability to touch-to-slide that won't cover all use cases.

Ultimately I am trying to get lazy loading working, but need to know which slide I am on so I can determine what slides/images to load. 

Thanks again!

**Comment by mrbinky3000** [comment]
The slides trigger a css animation in the Slider component.  You can either tap into the css animation api to listen for the animation to finish (this is the best option, but check icanuse to see if all your target browsers support it first).  OR, you can use a timer to trigger your callback.  Attach it to the buttons in your carousel and have the delay match the length of your animation.

Also keep in mind, people will click on your nav buttons before the animation is complete, so you'll have to come up with a strategy for throttling your callback.

**Comment by jamesmosier** [comment]
Makes sense. Thanks for the quick response!

**Comment by mrbinky3000** [comment]
Glad I could help! Feel free to re-open this if you discover any new problems along the way.

**Comment by mrbinky3000** [comment]
There is a higher order component called WithStore() that you can use to wrap any custom component that you create.  It contains a lot of useful values that get updated automatically.  So, theoretically, you can use react componentDidUpdate as a callback of sorts, listening for changes to things you care about, like the current slide.

Using WithStore, you can get the value of the current left-hand-most visible slide (currentSlide).  And there is also a value for the total number of slides to show at one time (visibleSlides).  Use those two values to figure out which slides are currently visible. 

You can place your new custom component that's wrapped with WithStore() higher order component as a child of each Slide component.  This new custom component could then load images for you when the slides become visible, or load the next X images before they slide into view.

I hope that helps, but yes, there are ways to tap into this information and then leverage React's built-in lifecycle event componentDidUpdate() to listen for changes to key props.

**Comment by mrbinky3000** [comment]
Most of the components in this library use the WithStore() HOC in their index.js files.  That is how we "decorate" each of our components with props.  Check out how we do it to get a better idea.   Start with Dot for something simple.  Move on to Image for a more complex example.

**Comment by jamesmosier** [comment]
Awesome, thanks again for the guidance! 🙏
