### ISSUE TITLE
Found typing error for CarouselProviders

### ISSUE THREAD

**Issue by zoeyzou** [express-labs/pure-react-carousel#132]
#131 <= this is the PR I've made.

Found the problem while tring to use this library in a typescript react project. while you define the type of props, usually the props for library should be included so it can be spreaded. However, in the library typing, CarouselProviderProps is not exported. Instead, CarouselProviderState is. So I changed the export.

Please take a look and merge asap..

**Comment by mrbinky3000** [comment]
Merged.  Thanks!  pure-react-carousel@1.19.3
