### ISSUE TITLE
on newest version the type file is gone

### ISSUE THREAD

**Issue by zoeyzou** [express-labs/pure-react-carousel#133]
I just installed 1.19.3, and the typing file cannot be found. I took a look into the installed package, this is the folder/file structure: 
```
- pure-react-carousel
  - dist
    - index.cjs.js
    - index.cjs.js.map
    - index.es.js
    - index.es.js.map
    - react-carousel.cjs.css
    - react-carousel.cjs.css.map
    - react-carousel.es.css
    - react-carousel.es.css.map
  - license.md
  - package.json
  - readme.md
```

I was using 1.19.0 yesterday, and I can still find the typing file while importing some components. Can you check what's going on?

**Comment by mrbinky3000** [comment]
Gah... I left the typing files out of the package....   package.json
"files" property.  I will fix.

**Comment by mrbinky3000** [comment]
pure-react-carousel@1.19.4

re-added typings folder to the published package

![Screen Shot 2019-04-11 at 9 45 04 AM](https://user-images.githubusercontent.com/161068/55962259-8627e500-5c3e-11e9-8297-da3591bbe525.png)
