### ISSUE TITLE
Support for styled components

### ISSUE THREAD

**Issue by yyynnn** [express-labs/pure-react-carousel#135]
Please consider use of styled components or give static classnames to your elements.
It is pain to do ssr.

**Comment by yyynnn** [comment]
It would be nice to hash root/parent className at a build-time or if an external className provided (e.g. with styled components) just pass it down to children.

**Comment by tim-steele** [comment]
@yyynnn I am not sure I understand what you are asking? We use static class names on components, and provide ways to pass class names to components.
