### ISSUE TITLE
Is there a way to focus only on keyboard tab 

### ISSUE THREAD

**Issue by caterinavanherpt** [express-labs/pure-react-carousel#140]
Is there a way to render out the focus div on the Slide component only on keyboard tab and not on mouse click or touch?

**Comment by mrbinky3000** [comment]
The focus ring is just CSS applied to the Slide component.  You could add your own mouse click and touch event handlers and conditionally add your own css class to the Slide component that hides the focus ring.

**Comment by mrbinky3000** [comment]
Did that work for you?
