### ISSUE TITLE
Uncaught TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by VitaliiTsurkan** [express-labs/pure-react-carousel#142]
Please provide a full example how to use setStoreState because I tried to do it by myself (as written in docs) and whole my page where I used it just invisible. I tried to use this.props.carouselStore.setStoreState({ currentSlide: 2 }).
My page became invisible when i add export withStore

**Comment by VitaliiTsurkan** [comment]
Error is  Uncaught TypeError: Cannot read property 'state' of undefined
my export
```
export default WithStore(MyComponent, state => ({
    currentSlide: state.currentSlide,
  }));
```

**Comment by mrbinky3000** [comment]
You can look at the index.js file for most components in the src folder for examples of how to use WIthStore.

Here is a simple example for the Dot component:
https://github.com/express-labs/pure-react-carousel/blob/master/src/Dot/index.js

```jsx
import Dot from './Dot';
import WithStore from '../Store/WithStore';

export default WithStore(Dot, state => ({
  currentSlide: state.currentSlide,
  totalSlides: state.totalSlides,
  visibleSlides: state.visibleSlides,
}));
```

If state is undefined, you may be using WithStore on a component located outside of your `<CarouselProvider>` tags.

```jsx
<CarouselProvider>
  // WithStore only works on components in between your CarouselProvider tags.
</CarouselProvider>
```
