### ISSUE TITLE
Updating rollup-plugin-postcss stopped the build extracting CSS correctly

### ISSUE THREAD

**Issue by GarySiu** [express-labs/pure-react-carousel#144]
A clean install of v1.19.5 now outputs all css files as `[object Object]`
v1.19.4 works as expected.

**Comment by mrbinky3000** [comment]
Yep, this was a bug.  Updated post-css to fix a security issue.  Latest post-css only works with a newer version of rollup.  Just updated rollup right now.

Please try v.1.19.6 really quick and let me know what happens.

**Comment by GarySiu** [comment]
There's some deprecation warnings now but seems to work 👍 

`(!) node-resolve plugin: The onwrite hook used by plugin node-resolve is deprecated. The generateBundle hook should be used instead.`

**Comment by mrbinky3000** [comment]
I will look into getting rid of those deprecation warnings in the near future.  I just wanted to get you fixed first.
