### ISSUE TITLE
How to change <Dot> active style?

### ISSUE THREAD

**Issue by VitaliiTsurkan** [express-labs/pure-react-carousel#147]
How can I change <Dot>  active style?
Could you provide an example how to do that?
Thanks in advance!

**Comment by tim-steele** [comment]
@VitaliiTsurkan - In the documentation for the <Dot> component, you can see the html out put by the component:
```
<button class="carousel__dot carousel__dot--[slide] [carousel__dot--selected] [props.className]" onClick="[props.onClick]" disabled="[props.disabled]" ...props>
  [props.children]
</button>
```

If the dot is active it gets the `carousel__dot--selected` class.

**Comment by VitaliiTsurkan** [comment]
@tim-steele  Actually I don't understand where I should redefine this class, could you provide an example, please?

**Comment by harrysmartdevs** [comment]
Could you please re-open this issue?
I also got the same problem with this guy, but I don't see any solution here yet.

**Comment by tim-steele** [comment]
@harrysmartdevs a CSS class is provided for the active dot: `carousel__dot--selected`. This allows you to write CSS for the active dot. Also, the props take a className property that can have a class name passed in. Either of these would allow you to style the active dot.

**Comment by dqii** [comment]
```
.carousel__dot--selected {
	background-color: #000;
}
```

I added this but wasn't able to get any changes. Do you have a more clear example?

**Comment by gazpachu** [comment]
In case you use CSS-in-JS:

```
export const CarouselDot = styled(Dot)<DotProps>`
  background-color: ${({ isActive }) =>
    isActive ? color('primary') : COLORS.GRAY.L4};
  width: 7px;
  height: 7px;
  border-radius: 100%;
  margin: 0 ${SPACING.L1};
`;
```

```
<CarouselDots
            renderDots={({ currentSlide }) =>
              CAROUSEL_IMAGES.map((image, index) => (
                <CarouselDot
                  slide={index}
                  isActive={currentSlide === index}
                  key={`dot-${index}`}
                />
              ))
            }
          />
```
