### ISSUE TITLE
How to access the disabled props from Dot in a DotGroup

### ISSUE THREAD

**Issue by arnaudambro** [express-labs/pure-react-carousel#148]
Hi there, 

I would like to make all the `Dot`s from a `DotGroup` always enabled, never disabled, how could I do ?

**Comment by mrbinky3000** [comment]
You'll have to create your own DotGroup-like component.  It's just a
wrapper that makes a loop and repeats Dot components.  I would look at the
source code for  DotGroup, clone it, and make your changes.  You could
clone it as-is and just ensure that Dots are always enabled.

**Comment by arnaudambro** [comment]
That's what I did finally: I forked your (great) project and added the change.
Thanks !
