### ISSUE TITLE
Callback When Dragging/Swiping Slides?

### ISSUE THREAD

**Issue by ErnestGrey** [express-labs/pure-react-carousel#149]
I can't seem to figure out how to notify the Dots (thumbnails) that the slide has changed when the user swipes/drags to go forward or backward through the slides. 

I have a selected state css style for the dots when the corresponding slide is "active". It works just fine when using buttons or clicking on the dots themselves, but I don't know how to notify the dot(s) of a slide change when the user swipes/drags. Anyone have a solution for this? Ideally there would be an onChange event on the CarouselProvider or the Slider.

**Comment by pragmatic84** [comment]
Having a similar problem. I'm trying to call a function 'onDragStart' in order to update my 'activeSlide' within my state (trying to add some animations to the active slide).

I've tried adding this prop to my Slide component but nothing is happening.

**Comment by mrbinky3000** [comment]
This feature does work. Here is a video of the dots being updated after a drag on our demo page: https://express-labs.github.io/pure-react-carousel/

![Screen Recording 2019-06-26 at 10 11 AM](https://user-images.githubusercontent.com/161068/60187065-ed474580-97fa-11e9-813e-65d953b4a8c1.gif)

I have a feeling that your Dot components are not descendants of CarouselProvider.   

Pure React Carousel's various components use React's "context" API to communicate with each other. The context is declared in CarouselProvider.  Therefore every Pure React Carousel has to be a descendant of CarouselProvider.  They don't need to be direct descendants. 

```jsx
// this won't work (pseudo code example)
<CarouselProvider>
</CarouselProvider>
<Dot />
```

```jsx
// this will work (pseudo code example)
<CarouselProvider>
   <Dot/>
</CarouselProvider>
```

```jsx
// this will also work (pseudo code example)
<CarouselProvider>
   <div>
      <div>
        <div>
           <Dot/>
        </div>
      </div>
    </div>
</CarouselProvider>
```

**Comment by mrbinky3000** [comment]
@pragmatic84 Your issue is different.  Can you copy your comments to a new issue thread?

**Comment by ErnestGrey** [comment]
@mrbinky3000 

Yes, when using a `DotGroup` this works, however, I do have my `<Dot>` components within the `<CarouselProvider>` and when I swipe, the dots do not update to active.

Here is my code:

```
const Carousel = ({ carouselItems }: Props) => {
  const [selectedImageIndex, setSelectedImageIndex] = useState(0);
  const classes = useStyles();

  const handleThumbnailSelection = (index: number) => {
    setSelectedImageIndex(index);
  };

  const handleBackButtonPressed = () => {
    if (selectedImageIndex === 0) {
      return;
    } else {
      setSelectedImageIndex(selectedImageIndex - 1);
    }
  };
  const handleNextButtonPressed = () => {
    if (selectedImageIndex === carouselItems.length - 1) {
      return;
    } else {
      setSelectedImageIndex(selectedImageIndex + 1);
    }
  };

  return (
    <CarouselProvider
      naturalSlideWidth={950}
      naturalSlideHeight={1000}
      totalSlides={carouselItems.length}
      className={classes.carousel}
    >
      <Slider>
        {carouselItems.map(({ media }, index) => {
          return (
            <Slide
              key={index}
              index={index}
              className={classes.carouselImageWrapper}
            >
                <Img className={classes.carouselImage} {...media} />
            </Slide>
          );
        })}
      </Slider>
      <ButtonBack
        onClick={handleBackButtonPressed}
        className={`${classes.carouselControl} ${classes.carouselControlLeft}`}
      >
        <IconButton
          aria-label="Back"
          disableRipple
          className={classes.carouselControlButton}
        >
        </IconButton>
      </ButtonBack>
      <ButtonNext
        onClick={handleNextButtonPressed}
        className={`${classes.carouselControl} ${classes.carouselControlRight}`}
      >
        <IconButton
          aria-label="Next"
          disableRipple
          className={classes.carouselControlButton}
        >
        </IconButton>
      </ButtonNext>
      <div className={classes.carouselThumbs}>
        {carouselItems.map(({ thumbnail }, index) => (
          <Dot
            key={index}
            slide={index}
            className={classes.carouselThumbnailWrapper} 
            onClick={handleThumbnailSelection.bind(null, index)}
          >
            <Img className={classes.carouselThumbnail} {...thumbnail} />
          </Dot>
        ))}
      </div>
    </CarouselProvider>
  );
};
```

**Comment by mrbinky3000** [comment]
Anywhere I can see the code in action somewhere so I can inspect it?

**Comment by pragmatic84** [comment]
> @pragmatic84 Your issue is different. Can you copy your comments to a new issue thread?

Done, see here https://github.com/express-labs/pure-react-carousel/issues/155

**Comment by ErnestGrey** [comment]
@mrbinky3000, I can try to put an example up somewhere, but it would be helpful if there was an example provided similar to the real world examples you have on your demo page. Where you have images as `<Dot>` components that are not within a `<DotGroup>`

**Comment by case12** [comment]
Having a similar issue. A callback on the Sliders or Carousel Provider like `onSlideChanged` would be super helpful. Don't see it in the docs but you could follow the advanced carousel usage section and get passed the carousel props including current slide and check in componentWillReceiveProps for when it changes. Not an ideal solution though.

**Comment by vignitres** [comment]
> Having a similar issue. A callback on the Sliders or Carousel Provider like `onSlideChanged` would be super helpful. Don't see it in the docs but you could follow the advanced carousel usage section and get passed the carousel props including current slide and check in componentWillReceiveProps for when it changes. Not an ideal solution though.

Any news on this feature?
