### ISSUE TITLE
Module not found: Error: Can't resolve 'pure-react-carousel' with version v1.21.0

### ISSUE THREAD

**Issue by SwapnilGatha** [express-labs/pure-react-carousel#152]
Issue with recent version v1.21.0 on upgrading from v1.19.0

**Comment by SwapnilGatha** [comment]
@express-crowbot

**Comment by tim-steele** [comment]
@SwapnilGatha where are you seeing that happen? In your project in general? When you start your application?

**Comment by sethomas** [comment]
I very jankily was doing this:
```
@import "./node_modules/pure-react-carousel/dist/react-carousel.es.css";
```

Which is now gone from `1.21.0`, causing:
```
Module build failed: ModuleNotFoundError: Module not found: Error: Can't resolve './node_modules/pure-react-carousel/dist/react-carousel.es.css'
```

For an immediate fix, I am going to hard code `1.21.0` as the version

**Comment by mhigley** [comment]
I can confirm that 1.21.0 is having the issue. Here's my terminal input on install and after `gatsby develop`:

**Comment by tim-steele** [comment]
@sethomas @mhigley Can you please try 1.21.1?

**Comment by mhigley** [comment]
@tim-steele 
pure-react-carousel@1.21.1 did the trick! Thanks!! <3

**Comment by tim-steele** [comment]
@sethomas @SwapnilGatha did 1.21.1 it fix your issues as well?

**Comment by sethomas** [comment]
@tim-steele what a delightfully fast response, good to go on `1.21.1`, I see the `/dist` folder and files so I can continue to jankily import the css, thanks!

**Comment by tim-steele** [comment]
Marking this as resolved.

**Comment by SwapnilGatha** [comment]
yes... pure-react-carousel@1.21.1 works ! thanks @tim-steele
