### ISSUE TITLE
NPM module load issue

### ISSUE THREAD

**Issue by PraveenVerma17** [express-labs/pure-react-carousel#153]
Hi,

We have noticed that sometime when we run npm install pure-react-carousel does not create dist folder inside npm node_module/pure-react-carousel which breaks our build. 

Would you be able to help me on this?

**Comment by tim-steele** [comment]
@PraveenVerma17 are you not seeing a dist folder? What version are you using?

**Comment by PraveenVerma17** [comment]
Hi

Sorry, We have removed this component from our application. I will check our commits and let you know the version.
