### ISSUE TITLE
slides containing text are overflowing and appear cut because of the way naturalSlideWidth and naturalSlideHeight are setup

### ISSUE THREAD

**Issue by laurencejennings** [express-labs/pure-react-carousel#154]
I'm having some trouble getting a carousel with slides containing text to work correctly. Since I have to set the naturalSlideHeight and Width a-priori, it results in the slides overflowing and being cropped when the viewport of the device gets smaller (text size stays the same so the slide height should increase for smaller viewports).

I don't know if there is something I'm missing, how would it be possible to set the natural slide height as the height of the "highest" slide in my slideshow? And how would I go to keep that value responsive for different viewport sizes?

Thanks a lot

**Comment by mrbinky3000** [comment]
These are things people discover when doing responsive web design.  Text
pushes a box taller the smaller the width becomes.   I would research how
others have solved this problem over the years.  There are lots of
tutorials on the net.  Things you can do off the top of my head...

1) Mobile first design.  Make the text fit your smallest targeted device
first.
2) Relative font sizes.  Font sizes that adjust to the size of the
container.
3) Progressive enhancement:  don't show the same text for small devices as
larger ones.  Show less text in the smaller device.

Lastly, pure react carousel does not HAVE to be responsive.  There are
directions in the documentation on how you can force your carousel to be a
fixed width size.

**Comment by mrbinky3000** [comment]
![Screen Shot 2019-06-26 at 9 14 14 AM](https://user-images.githubusercontent.com/161068/60182701-cdac1f00-97f2-11e9-89e3-d2fc14d991c7.png)
