### ISSUE TITLE
Background Spinner

### ISSUE THREAD

**Issue by engmsilva** [express-labs/pure-react-carousel#160]
How to remove the gray background when the spinner is calling Let the transparent background spinner over the last image before loading new images.
The code below does not work:
`.masterSpinnerContainer___1Z6hB > .carousel__master-spinner-container{
  background-color: transparent;
 }`

**Comment by mrbinky3000** [comment]
I'm pretty sure you just need to do use `.carousel__master-spinner-container { background-color: transparent' }`  Just make sure you declare your CSS after you import the CSS for pure-react-carousel.  Check your browser's developer tools to make sure your CSS is not getting overridden by our CSS.

**Comment by mrbinky3000** [comment]
Closing for now.  Reopen if it doesn't work.
