### ISSUE TITLE
ImageWithZoom Example

### ISSUE THREAD

**Issue by malikgenius** [express-labs/pure-react-carousel#163]
Hi sorry for the stupid question, i couldnt find any example code for ImageWithZoom, how to use it, i dont want slides but zoom for my static image, please guide me towards those easy to follow examples ...

**Comment by maxacarvalho** [comment]
@malikgenius simply replace the `<Image />` with `<ImageWithZoom />`, same props are necessary. You have also the `srcZoomed` one available for a bigger image if you want to.
