### ISSUE TITLE
Problem importing pure-react-carousel: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by FootyNumb3rs** [express-labs/pure-react-carousel#165]
I'm attempting to utilize pure-react-carousel for my React project but the file won't import properly. 

When the following import statements: 

`import {
  CarouselProvider,
  Slider,
  Slide,
  ButtonBack,
  ButtonNext
} from "pure-react-carousel";`

`import "pure-react-carousel/dist/react-carousel.es.css";`

Without adding any components, I get  -- Cannot read property 'state' of undefined

Referencing the following line: `return i.state = t(_extends({}, r.carouselStore.state)), i.updateStateProps = i.updateStateProps.bind(i), i;`

Also, a few questions about the component itself. 

1. I'm interested in this because it allows one to independently vary the height and width. Can I also control how the contained image is cut? Where to align it, etc? 

2. Does this support captions?

**Comment by AKosorukov** [comment]
The same problem.
