### ISSUE TITLE
Add note about responsiveness

### ISSUE THREAD

**Issue by ElForastero** [express-labs/pure-react-carousel#168]
I think would be better no make a note that this carousel is responsive and best-suited right for images, not fixed-width/height content. It was not clear from demos and readme.

**Comment by mrbinky3000** [comment]
![Screen Shot 2019-09-04 at 9 26 31 AM](https://user-images.githubusercontent.com/161068/64258946-1f111280-cef6-11e9-81f5-b6221b4e1aba.png)
That information is in there already.  Perhaps we can add a bullet point to the intro at the top of the documentation.

**Comment by mrbinky3000** [comment]
Actually, there already is a bullet point in the intro.
