### ISSUE TITLE
Change number of visible slides in mobile

### ISSUE THREAD

**Issue by anupchrome** [express-labs/pure-react-carousel#172]
It has been said in the documentation that the slider in responsive but there is no option to change the number of visible slides in mobile. Many sliders like OWL and SLICK sliders provide that functionality, in which after a break-point (Eg: 768px) the number of visible slides decreases. 
If I show 3 slides in desktop at the same time then if I open it in mobile, it still shows 3 slides in mobile which looks very congested. 
Please add the functionality to decrease the number of visible slides after a breakpoint.
Thanks

**Comment by tim-steele** [comment]
@anupchrome This library was built to not be prescriptive. We were able to achieve what you are requesting on express.com by using the visibleSlides property and wrapping the carousel in the breakpoint logic. This allows people who use pure reac carousel to set their own breakpoints, breakpoint logic, and responsive design without trying to "fight" the logic of pure react carousel.

**Comment by parkersweb** [comment]
Just a brief note for others who might follow looking for this functionality. This is relatively simple to achieve using [react-responsive](https://www.npmjs.com/package/react-responsive).

At the top of the component you'll need:
```
import { useMediaQuery } from "react-responsive";
```
Inside my component I've then got a const using the hooks react-responsive provides:
```
  const isDesktop = useMediaQuery({
    query: "(min-device-width: 1024px)",
  });
  const isTablet = useMediaQuery({ query: "(min-device-width: 600px)" });
  const slideCount = isDesktop ? 3 : isTablet ? 2 : 1;
```
CarouselProvider then just needs updating so that `visibleSlides={slideCount}`

**Comment by adiusz** [comment]
@parkersweb thanks so much, this is exactly what I needed and it works!

**Comment by adiusz** [comment]
Little update.
The solution you @parkersweb metioned worked on localhost perfectly. But when I pushed website to netlify I saw strange thing. Everytime I get on the page on my computer, visibleSlides must be equal to 1 (cause 1 slide is visible obviously). But when I open dev tools, choose some mobile device resolution, and then close dev tools to get normal laptop resolution - I can see 3 slides like it should be. It looks like that lib is loaded after site is rendered. Any idea how to prevent it?

**Comment by parkersweb** [comment]
@adiusz Hmmm - that's odd. I'm not sure why that would work correctly on localhost then. Is is possible it's an SSR issue: https://github.com/contra/react-responsive/issues/239 ?

**Comment by adiusz** [comment]
Thing is I'm using GatsbyJS, so SSR is not my case. 
When I get to the page, slider is showing 1 pic, but when I navigate to another page, and then get back on home page (where slider is) - it's showing 3 pics like it should. I tried react-sizes and react-responsive. Same effect on both.

**Comment by adiusz** [comment]
You might be right. I checked few posts and I decided to do it manually - just rendering 2 elements and by using CSS media queries hiding one of them on specific breakpoint. Thanks for help anyway :)

**Comment by looeyf** [comment]
> Little update.
> The solution you @parkersweb metioned worked on localhost perfectly. But when I pushed website to netlify I saw strange thing. Everytime I get on the page on my computer, visibleSlides must be equal to 1 (cause 1 slide is visible obviously). But when I open dev tools, choose some mobile device resolution, and then close dev tools to get normal laptop resolution - I can see 3 slides like it should be. It looks like that lib is loaded after site is rendered. Any idea how to prevent it?

Using react hooks it will work. I have changed the slideCount to a useState and then applied it inside a useEffect to change the value of slideCount every time the isDesktop or isTablet has its value changed.

**Comment by AjayiMike** [comment]
> Little update. The solution you @parkersweb metioned worked on localhost perfectly. But when I pushed website to netlify I saw strange thing. Everytime I get on the page on my computer, visibleSlides must be equal to 1 (cause 1 slide is visible obviously). But when I open dev tools, choose some mobile device resolution, and then close dev tools to get normal laptop resolution - I can see 3 slides like it should be. It looks like that lib is loaded after site is rendered. Any idea how to prevent it?

Are you using Nextjs? If yes, this is likely an ssr Issue. You can combine the media query result with usestate and useEffect like this

`const [slideCount, setSlideCount] = useState(1);
  const isDesktop = useMediaQuery({
        query: "(min-device-width: 1024px)",
    });
    const isTablet = useMediaQuery({ query: "(min-device-width: 600px)" });

    useEffect(() => {
        setSlideCount(isDesktop ? 5 : isTablet ? 3 : 1);
    }, [isDesktop, isTablet]);`
