### ISSUE TITLE
Tab index of elements within a <Slide>

### ISSUE THREAD

**Issue by conor-lacey** [express-labs/pure-react-carousel#173]
I have a use-case where the content of a slide contains a link, and this is causing an issue with the keyboard navigation of the carousel. Slides that aren't visible have `tabIndex="-1"` which prevents them from being reached by the keyboard, but if the slide's content has a link then this link is focusable and will be navigated to. 

Is there a way for a slide's inner content to inherit the tab index?

Some example code and a [CodeSandbox](https://codesandbox.io/s/reverent-ride-0uvxl) which  demonstrates the issue.
```jsx
<CarouselProvider
  totalSlides={6}
  visibleSlides={2}
  step={1}
  naturalSlideWidth={100}
  naturalSlideHeight={50}
>
  <Slider>
    <Slide index={0}>I am the first Slide.</Slide>
    <Slide index={1}>I am the second Slide.</Slide>
    <Slide index={3}>I am the third Slide.</Slide>
    <Slide index={4}>I am the fourth Slide.</Slide>
    <Slide index={5}>
      I am the fifth Slide, and I have a <a href="/">link</a>
    </Slide>
    <Slide index={6}>I am the sixth Slide.</Slide>
  </Slider>
  <ButtonBack>Back</ButtonBack>
  <ButtonNext>Next</ButtonNext>
  <DotGroup />
</CarouselProvider>
```

**Comment by tim-steele** [comment]
@conor-lacey I don't think we can start applying tab index to the content inside the slide without parsing through all the content every time a slide is changed. Also, some people may want the opposite, where if a link is in content, then tabbing to it may navigate there.

Can you set the tab index of the link based on whether the current slide is active or not? That may be a solution.
