### ISSUE TITLE
Feature: React Hooks?

### ISSUE THREAD

**Issue by raymondsze** [express-labs/pure-react-carousel#175]
I really love the Context API, so I could have many control on how component could be customised and placed.

I am trying to replace the components like ButtonFirst, ButtonBack, ... with Material-UI.

I know we could customise the look and feel using the css.
But sometimes we may want to integrate with framework that using jss, or even replace the entire component with some existing component in other framework.

Here is how I do it currently.
```jsx
import { ButtonFirst } from 'pure-react-carousel';
import Button from '@material-ui/core/Button';

const CustomButtonFirst = React.forwardRef((props, ref) => <Button component={ButtonFirst} ref={ref} {...props} />);

// This line is needed because the "disabled" is internal state of "ButtonFirst".
export default withStore(CustomButtonFirst, state => ({ disabled: state.currentSlide === 0 }));
```

You could see the "disabled" logic have to be injected via "withStore". It means that I am assumed to know how the "disabled" is derived inside ButtonFirst component.

It would be nice if we could do something like this instead...

```jsx
import { useButtonFirst } from 'pure-react-carousel';
import Button from '@material-ui/core/Button';

const CustomButtonFirst = React.forwardRef((props, ref) => {
   const buttonProps = useButtonFirst();
   return <Button ref={ref} {...buttonProps} {...props} />);
});
export default CustomButtonFirst;
```

Then I could have full control how ButtonFirst looks like without knowing any logic inside ButtonFirst component and no matter what styling solution I using as well.

Similar Hooks could be done as well like useButtonNext(), useButtonPlay(), useDot(slideIndex), etc.

Thanks.

**Comment by tim-steele** [comment]
I am not sure I understand the issue - can you provide more detail?

Do you want to be able to pass additional props to button that are not currently supported by the button? Can you show me an example or a PR that provides additional details on what you are trying to solve?

**Comment by raymondsze** [comment]
Now the ButtonFirst, ButtonBack, ButtonNext and ButtonLast are actual components that with the <button> tag. I would like to integrate those button to Material-UI (i.e change the button to IconButton). IconButton is a React Component which underlying is a button component, so it could accept all the props that button could receive.

The issue here is I am not able to replace the ButtonFirst/ButtonBack/ButtonNext/ButtonLast to Material-UI's IconButton as it is not "a simple css override". I have to implement all the button logic myself with "withStore" hoc helper. Although these buttons are simple to implement, what I suggest here is to provide hooks that allow us to grab the corresponding props that the ButtonFirst/ButtonBack/ButtonNext/ButtonLast/etc using. (i.e separate the props and state to React Hook and expose them).

**Comment by tim-steele** [comment]
@raymondsze I think the best way to propose this is via a PR that shows what you are asking. It sounds like you are asking to replace the carousel buttons, with Material UI buttons.

If you wanted to get a draft PR that developers could look at and comment on that would be great. Once comments have been discussed on it, the draft could be finalized and submitted as a mergeable PR.
