### ISSUE TITLE
Variable Height Support Needed

### ISSUE THREAD

**Issue by yuchant** [express-labs/pure-react-carousel#176]
If slide content contains any text + an intrinsic aspect image, the aspect ratio of the entire block will change for every pixel change in container width due to text not scaling.

I'm trying to calculate the aspect ratio of the largest element, but this would be nice to bake in. Critical even IMO.

**Comment by tim-steele** [comment]
Can you provide more details on the issue you are trying to solve? From what I understand, you are saying that each slide in the carousel is a different height?

**Comment by GuidovdRiet** [comment]
I am currently facing the same problem, are there any known workarounds to this problem?

**Comment by omasback** [comment]
If a slide's height is determined by its text content then it will be different heights at different widths. You cant know the slide's aspect ratio in advance. Most carousels in this situation will attempt to render once and then measure all the slides text-determined heights and then set the wrapper to the maximum. This carousel has the best API of any on npm and it would be great if it could support this behavior.
