### ISSUE TITLE
Dot Handling when Visible Slides > 1 is unintuitive

### ISSUE THREAD

**Issue by yuchant** [express-labs/pure-react-carousel#177]
I think the dot handling when there is more than one visible slide is very unintuitive.. there's either N disabled inputs or N `--selected`.

Does anybody have a solution for handling slide groups? 

I might need to do something weird like inspecting DOM for selected and hiding all but one on slide change/visibleslide change.

![image](https://user-images.githubusercontent.com/292732/65095496-615d4800-d9fc-11e9-8f8f-08a3bf54cb65.png)

**Comment by yuchant** [comment]
I've added grouped slide counts like so for anybody looking:
```
/**
 * Render carousel dots by group
 */
const renderDots = (props) => {
	const { totalSlides, visibleSlides } = props
	const slideGroups = Math.ceil(totalSlides / visibleSlides)
	if (slideGroups <= 1) {
		return
	}
	return (
		<div className="Carousel__Dots">
			{[...Array(slideGroups)].map((_, i) => (
				<Dot
					slide={i * visibleSlides}
					aria-label={`Move Carousel to slide group ${i + 1}`}
				></Dot>
			))}
		</div>
	)
}
```

**Comment by tim-steele** [comment]
@yuchant we used to do groups of dots on the Express website. I would have to look through old code to find an example, but I know it is doable.

**Comment by hkrobotics** [comment]
any updates ?

**Comment by Darkxleo** [comment]
any updates on this issue?
