### ISSUE TITLE
Slide is array of images fetched from remote API?

### ISSUE THREAD

**Issue by dominick-designs** [express-labs/pure-react-carousel#178]
Is it possible to have each slide dynamically loaded from a remote API? 

Rather than using static images from a local array, is it possible to integrate the results of a fetch so that ```<Slide index={0}>{<img src="https://via.placeholder.com/228x290.png" alt="" />}</Slide>``` are automatically created based on a map iteration of a fetch response?

I hope it's ok if I post this question here.

**Comment by tim-steele** [comment]
@dominick-designs the idea behind this carousel is to not be too prescriptive and include too many dependencies. To accomplish what you are asking, you would just need to put the fetch in a wrapper and pass the results in via the array.
