### ISSUE TITLE
Carousel sometimes freeze after drag.

### ISSUE THREAD

**Issue by Gratisvampier** [express-labs/pure-react-carousel#179]
Hi, found bug. When dragging, sometimes deltaX value don't clear which causes a slider display error.

![screenshot_3](https://user-images.githubusercontent.com/7389693/65244497-56d1aa00-daf3-11e9-88ea-cce2788e5cf8.png)

**Comment by tim-steele** [comment]
Can you please provide more details for this bug? Browser, OS, etc.

**Comment by Gratisvampier** [comment]
Browser - Google Chrome Version 77.0.3865.90
OS - Ubuntu 18.04.3 LTS

**Comment by EldRoos** [comment]
I get this error too: In Chrome 77, Internet Explorer 11.

But works in Firefox 69 and Opera 58.

Unkown: Edge 42.

Using Windows 10.

Just drag fast/long and it will become unsynced. Pressing DotGroup/Dots after will not sync.

**Comment by tim-steele** [comment]
@EldRoos @Gratisvampier I am looking at it in our demo and I am unable to reproduce it. I tried both very fast dragging and long dragging.

I believe you but I am unable to reproduce it. If you are seeing it, is it something you are willing to submit a PR for a fix?

**Comment by third774** [comment]
@tim-steele I'm also running into this issue and have a theory as to what might be causing it.

It looks like the touch move event handler cancels the timer before setting up a new one.
https://github.com/express-labs/pure-react-carousel/blob/b8d6e36eae4a61f5599e8ae900f72c29eb26bdf1/src/Slider/Slider.jsx#L333

But I don't think this happens for mouse move events. The timer being set here _may_ be overwritten if multiple mouse move events fire in rapid succession.
https://github.com/express-labs/pure-react-carousel/blob/b8d6e36eae4a61f5599e8ae900f72c29eb26bdf1/src/Slider/Slider.jsx#L222
