### ISSUE TITLE
Package is minified in development

### ISSUE THREAD

**Issue by MaxPort** [express-labs/pure-react-carousel#181]
I found that your package is minified in development so it is a pain to debug. Is there anyway to stop this?

![Screenshot 2019-10-01 at 16 45 04](https://user-images.githubusercontent.com/5747320/65978065-f0da1080-e46a-11e9-8e44-65fe3e66ca60.png)

**Comment by tim-steele** [comment]
I don't have insight into how your development environment, however, I know that we include the source maps with the Node module. If you include these, you should be able to see the source map in your debugger.

![image](https://user-images.githubusercontent.com/1490225/66047927-a43c1700-e4f6-11e9-817e-22ac7a07f9c6.png)
