### ISSUE TITLE
DotGroup prop renderDots is not working

### ISSUE THREAD

**Issue by MaxPort** [express-labs/pure-react-carousel#182]
I get the following error when trying to use the renderDots prop function on DotGroup. 

`Warning: React does not recognize the "renderDots" prop on a DOM element.`

When checking the code it looks like the renderDots prop is missing from the typing interface.

```
interface DotGroupProps {
    readonly children?: React.ReactNode;
    readonly className?: string;
    readonly dotNumbers?: boolean;
}
```

**Comment by tim-steele** [comment]
@MaxPort this is the Typescript implementation yes? Is this something you could submit a PR for?

**Comment by chungwong** [comment]
I believe the `renderDots` props is not in any releases yet.
So you will have to wait until the related commit got released.

**Comment by tim-steele** [comment]
@MaxPort it looks like two things are happening:
1. We aren't filtering the `renderDots` prop out of the props before sending the props downstream to the `renderDots()` function.
2. We didn't add it to the TypeScript interface.

Both of these require a patch. Is this something you would be willing to submit a PR for?

**Comment by MaxPort** [comment]
@tim-steele thanks for the reply. Yeah I will take a look at these and submit a PR if I can fix the issues.
