### ISSUE TITLE
Infinite loop, direction change when you reach the end.

### ISSUE THREAD

**Issue by danielbotn** [express-labs/pure-react-carousel#193]
**Describe the feature you'd like:**

The new "infinite" prop for introduced in version 1.23.0 is a very nice feature, but I was wondering if it would be possible to change the direction when the user has reached the end of the slides. So instead of going left all the way to the beginning, you would go to the right and end up at the beginning.  

**Suggested implementation:**

Maybe add a prop to the CarouselProvider.

**Describe alternatives you've considered:**

Here is a demo that shows a carousel that goes to the right after reaching the end [https://kenwheeler.github.io/slick/](https://kenwheeler.github.io/slick/)

**Comment by mrbinky3000** [comment]
How would this work?  You click on the right arrow to keep moving right.
Then you hit the last slide and clicking the right arrow makes you go
left?  That might have some accessibility implications.  I'm open to
discussion.

**Comment by tim-steele** [comment]
@danielbotn based on the Slick demo you posted and what you described, it looks like you are asking for the carousel to continue with the next slide appearing after the last side, and so on.

@mrbinky3000 has talked about ways this could be accomplished in other Issues (https://github.com/express-labs/pure-react-carousel/issues/60#issuecomment-406290767), but if it is something you need or would like to see I would encourage you to submit a pull request and become a contributor.

**Comment by dawidk92** [comment]
@tim-steele why this issue had been closed? I would find this feature extremely helpful.

**Comment by tim-steele** [comment]
@dawidk92 We would welcome a pull request if you would be open to working on the feature. In my comment above, I linked to where there has been discussion around how something like this could be implemented.
