### ISSUE TITLE
ButtonNextInterface exported instead of ButtonNextProps

### ISSUE THREAD

**Issue by Hetachi** [express-labs/pure-react-carousel#198]
- `pure-react-carousel` version: 1.23.0
- `react` version: 16.11
- `browser` used: Chrome
- `node` version: 12.11.1

### Relevant code or config:

```js
import React from 'react';
import { ButtonNextProps } from 'pure-react-carousel';
 interface ButtonNextProps {
    style?: React.CSSProperties;
  }
```

### What you did:

I want to make a type check for style, and was unable to do it for ButtonNext.

### What happened:

 Property 'style' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ButtonNextProps, any, any>> & Readonly<ButtonNextProps> & Readonly<{ children?: ReactNode; }>'

### Reproduction:

```js
<ButtonNext
        style={buttonStyle()}
 >
    {"Some text here I guess"}
</ButtonNext>
```

### Problem description:

I am unable to extend ButtonNextProps to add type check for style.

### Suggested solution:

Export ButtonNextProps instead of ButtonNextInterface

### Can you help us fix this issue by submitting a pull request?

Yes

**Comment by bcarroll22** [comment]
Awesome, thanks for pointing this out! We don't use TypeScript internally, so could you go ahead and submit the PR for this to help us out? Thanks!
