### ISSUE TITLE
Demo site stuck on "Loading Dev App..." message

### ISSUE THREAD

**Issue by alexpreynolds** [express-labs/pure-react-carousel#218]
Opening the [demo link](https://express-labs.github.io/pure-react-carousel/) shows the message "Loading Dev App..." in the top-left corner of the web browser. The browser seems stuck on this message. This occurs in the latest versions of Firefox and Chrome desktop browsers.

**Comment by alexpreynolds** [comment]
Console reports three error messages attempting to load `style.css` and `index.umd.js` files:

```
Failed to load resource: the server responded with a status of 404 ()
```

**Comment by Ryan-Willpower** [comment]
This happens because `gh-pages` doesn't include `dev/index.umd.js` and `dev/style.css` file, which is created when in development mode only (I mean when you run `npm run dev`)

**Comment by alexpreynolds** [comment]
I am not running `npm start`, but only trying to visit the [demo site](https://express-labs.github.io/pure-react-carousel/) linked from the Github repo.

**Comment by mrbinky3000** [comment]
I fixed it manually for now.  We need to update our automated build process
to run ghpages after a successful build.
