### ISSUE TITLE
The best way how to add gaps between slides ?

### ISSUE THREAD

**Issue by apincik** [express-labs/pure-react-carousel#221]
Is there any easy option how to add gaps between slides ? I've tried several approaches. I need correct padding when sliding one by one. When using margin, applying on slide or inner element, slider get broken, pushing last slide on new line block.

**Comment by bcarroll22** [comment]
Hey, thanks for using pure react carousel!

As stated in the [support question issue template](https://github.com/express-labs/pure-react-carousel/issues/new?template=Question.md), GitHub issues are a place to track bug fixes and feature requests, and questions opened as GitHub issues will be closed. I’d try using the support methods outlined there to get your questions answered. 

That said, we do appreciate you using the package. Can you do us a favor and make sure that any bugs or feature requests you open in the future use the provided templates? It helps us track and manage the issues internally. 

I’m going to close the now as not an issue, but good luck and happy coding!

**Comment by t4t5** [comment]
For people looking for an answer: https://stackoverflow.com/questions/60548361/how-do-i-add-spacing-to-my-slides-with-pure-react-carousel
