### ISSUE TITLE
Is there a way to let CarouselProvider naturalSlideHeight to be `auto`?

### ISSUE THREAD

**Issue by nicholaspung** [express-labs/pure-react-carousel#225]
Is there a way for the CarouselProvider container be responsive to only width? Currently, the implementation requires naturalSlideWidth={%} and naturalSlideHeight={%}. Or maybe adding a property which disables the need to specify a naturalSlideHeight by defaulting to making `height=auto`?

The use case would be to enter text as a slide. So when you resize the window, it still shows all the text, rather than the specified naturalSlideHeight, since it would cut off some text.

I realize most people use this carousel for images, but my use case is for a testimonial slider, where resizing makes the height different when it's responsive 😅. I haven't been able to find an example of someone doing something like that.

**Comment by angryeuan** [comment]
did you ever find a solution for this?

**Comment by KwanJunWen** [comment]
I ended up using another [npm package](https://www.npmjs.com/package/react-responsive-carousel) instead. @angryeuan

**Comment by danilo525** [comment]
Same problem here, any solution for this?

**Comment by zeeshan4242** [comment]
> Same problem here, any solution for this?

Just pass `isIntrinsicHeight` and it shall solve it.

**Comment by zeeshannagori** [comment]
> Same problem here, any solution for this?

  Just pass `isIntrinsicHeight` and it shall solve it.

**Comment by hirenkvaghasiya** [comment]
> > Same problem here, any solution for this?
> 
> Just pass `isIntrinsicHeight` and it shall solve it.

**_It worked for me_**  Cheers!
