### ISSUE TITLE
Dotgroup displaying incorrect number of dots when using visibleSlides prop

### ISSUE THREAD

**Issue by adamsoffer** [express-labs/pure-react-carousel#228]
- `pure-react-carousel` version: 1.24.1
- `react` version: 16.8.4
- `browser` used: Brave
- `node` version: 10.13.0

### Relevant code or config:

```js
<CarouselProvider
  naturalSlideWidth={100}
  naturalSlideHeight={125}
  totalSlides={slides.length}
  visibleSlides={3}
  step={3}
>
  <Slider>
    {slides.map((slide, i) => (
      <Slide key={i} index={i}>
        <Box sx={{ mx: 2 }}>{slide}</Box>
      </Slide>
    ))}
  </Slider>
  <Flex>
    <ButtonBack>
      <ArrowLeftIcon />
    </ButtonBack>
    <DotGroup />
    <ButtonNext>
      <ArrowRightIcon />
    </ButtonNext>
  </Flex>
</CarouselProvider>
```

### Problem description:
When using the `visibleSlides` prop, the number of dots representing the slides doesn't reflect the prop. For example, if I have 6 total slides, but set the visibleSlides prop to 3, there should only be 2 dots. But I'm seeing 6.

**Comment by T2GP-Sunny** [comment]
I am facing the similar situation.. any fix for this please

**Comment by polianych** [comment]
@T2GP-Sunny @adamsoffer  My workaround is to add empty slides to the last step if needed and use render prop for DotGroup component:

    const steps = 3

    const emptySlides = useMemo(() => {
        let slides = []
        let emptyCount = steps - (slidesItems.length % steps)
        if (emptyCount == steps) return slides
        for (let i = 1; i <= emptyCount; i++) {
            slides.push(
                <Slide
                    key={i + slidesItems.length}
                    index={i + slidesItems.length}></Slide>,
            )
        }
        return slides
    }, [slidesItems.length])

    const totalSlides = useMemo(() => {
        return slidesItems.length + emptySlides.length
    }, [slidesItems.length, emptySlides.length])

    const dots = props => {
        let d = []
        for (let i = 0; i < totalSlides / steps; i++) {
            let index = i * steps
            d.push(
                <Dot key={index} slide={index}>
                    <>
                        <div
                            className={classNames(
                                'border border-emerald-500 rounded-full m-1',
                                props.currentSlide >= index &&
                                    props.currentSlide < index + steps
                                    ? 'bg-emerald-500 h-3 w-3'
                                    : 'h-2 w-2',
                            )}></div>
                    </>
                </Dot>,
            )
        }
        return d
    }
JSX:
```
<CarouselProvider
      className="relative px-0 sm:px-12"
      naturalSlideWidth={100}
      naturalSlideHeight={100}
      isIntrinsicHeight={true}
      step={steps}
      dragStep={steps}
      visibleSlides={steps}
      totalSlides={totalSlides}>
      <Slider>
          {slidesItems.map((review, index) => (
              <Slide key={index} index={index}>
                  <ReviewSlide item={review} />
              </Slide>
          ))}
          {emptySlides}
      </Slider>
      <ButtonBack className="absolute hidden sm:block rounded-full border border-emerald-500 bg-white hover:bg-emerald-500 hover:text-white text-emerald-500 h-10 w-10 bottom-1/2 left-0">
          <FontAwesomeIcon
              icon={faAngleLeft}
              className="mt-1"
          />
      </ButtonBack>
      <ButtonNext className="absolute hidden sm:block rounded-full border border-emerald-500 bg-white hover:bg-emerald-500 hover:text-white text-emerald-500 h-10 w-10 bottom-1/2 right-0">
          <FontAwesomeIcon
              icon={faAngleRight}
              className="mt-1"
          />
      </ButtonNext>
      <DotGroup
          renderDots={props => (
              <div className="flex justify-center mt-6">
                  {dots(props)}
              </div>
          )}
      />
  </CarouselProvider>
```
