### ISSUE TITLE
Allow Slide to receive `style` props

### ISSUE THREAD

**Issue by ekohanyi** [express-labs/pure-react-carousel#232]
**Describe the feature you'd like:**
In the documentation it shows that the pseudo HTML that gets generated by Slide takes in `props.style`

<img width="905" alt="Screen Shot 2020-02-03 at 9 55 44 AM" src="https://user-images.githubusercontent.com/7947320/73677581-6a794980-466b-11ea-9737-c6fa15f39f24.png">

However `style` doesn't exist on the type declaration so it throws this error in TS 

![Screen Shot 2020-02-03 at 9 54 29 AM](https://user-images.githubusercontent.com/7947320/73677518-47e73080-466b-11ea-8baf-998985912b8f.png)

**Suggested implementation:**

Add `style` to the type declaration and make sure it can be passed from an instantiation of the Slide component

**Describe alternatives you've considered:**

I was able to work around this by having css classes that overrode the height of `li`, however i need those heights to be dynamic based on a variable so i need to pass the height down through `style`

**Teachability, Documentation, Adoption, Migration Strategy:**
Adding this to the existing Slide props documentation in the README

something like:

property | type | default | required | purpose
-------- | ---- | ------- | -------- | -------
style | [object&#124;null] | null | No | Optional inline style object to pass to root HTML element for each slide

**Comment by tim-steele** [comment]
@ekohanyi is this something you would be willing to open a pull request to fix?
