### ISSUE TITLE
Is it possible partially show the next item?

### ISSUE THREAD

**Issue by cesarvarela** [express-labs/pure-react-carousel#234]
Thanks!

**Comment by tim-steele** [comment]
Yes. We do it on express.com product pages on mobile devices. You just need to write your .css to show partial slides.

**Comment by acis** [comment]
For anyone looking for an answer to this,  adding  padding: 0 20px; (or any appropriate value) to the Slider component should do the trick.

**Comment by tomredman** [comment]
Surprisingly, this works:
```
visibleSlides={1.2}
```
