### ISSUE TITLE
Center active slide option

### ISSUE THREAD

**Issue by emmgfx** [express-labs/pure-react-carousel#242]
**Describe the feature you'd like:**

An option to center the active slide in the viewport would be great.

**Suggested implementation:**

-

**Describe alternatives you've considered:**

-

**Teachability, Documentation, Adoption, Migration Strategy:**

Probably the CarouselProvider component should have the option: `center={true}`. tiny-slider does it like this: https://github.com/ganlanyuan/tiny-slider#options

**Comment by mrbinky3000** [comment]
@emmgfx please check out this example.
https://codesandbox.io/s/pure-react-carousel-center-the-slides-xxe6l

**Comment by mrbinky3000** [comment]
https://stackoverflow.com/questions/60551722/how-do-i-center-the-slides-in-pure-react-carousel
