### ISSUE TITLE
Synthetic Event warning in console when tabbing through the slides

### ISSUE THREAD

**Issue by bishwenduk029** [express-labs/pure-react-carousel#244]
- `pure-react-carousel` version:1.25.2
- `react` version:16+
- `browser` used:google chrome
- `node` version:v12.14.1

### What you did:

Carousel Slider in horizontal mode. Then using tab key start tabbing through the slides.
### What happened:

When tabbing through the slides multiple instance of below warning was flashed in console.
“Warning: This synthetic event is reused for performance reasons” This warning is triggered when we try to access to a React synthetic event in an asynchronous way. Because of the reuse, after the event callback has been invoked the synthetic event object will no longer exist so we cannot access its properties.
### Suggested solution:

onFocus and onBlur are being passed synthetic events which are null, resulting in this error.
### Can you help us fix this issue by submitting a pull request?

I would love to. But not able to take some time out.

**Comment by mrbinky3000** [comment]
I just tabbed through every single slide on every singe example in our demo app and didn't encounter a warning.  Can you share your code?

**Comment by bishwenduk029** [comment]
Yes I also tested by removing a material-ui component and there were no errors in console. Apologize for false alarm. This package is amazing and very useful. Thanks for all the efforts.
