### ISSUE TITLE
Carousel direction right to left (RTL)

### ISSUE THREAD

**Issue by positimo** [express-labs/pure-react-carousel#255]
**Describe the feature you'd like:**

I'm looking for an easy way to switch the direction of the carousel items, so instead of index 0 being the leftmost item, it would be the rightmost item. Index 1 would be left of index 0 and so on.

The purpose in my case would be to display a chronological list of items where the latest is rightmost. If I start the carousel from the latest item (index 0) I would navigate leftwards to see the older items.

**Describe alternatives you've considered:**

Of course I could just reverse my list of items, but a problem arises when I need to load more older items. If my list is reversed, I would load more items when I reach index 0 (the leftmost item), but as soon as the items have loaded, I need to change the carousel index to represent the slide I was at before which causes complexity and a jump in the carousel view.

If carousel would support right to left direction, I would load more items at the leftmost slide, say index 10 for example, and the new items would position leftwards. No need to modify index or jump anywhere in the carousel.

More exotic alternative would be to change the carousel direction with CSS transform, and use reverse transform for the individual slides... But that would probably mess up something else, like the dragging for example.

**Teachability, Documentation, Adoption, Migration Strategy:**

I would imagine this could be a property of the `CarouselProvider`.

**Comment by tim-steele** [comment]
Could you just start the carousel at the end?

**Comment by positimo** [comment]
I could, but as explained above, I'd have to reverse the list and managing the list would become cumbersome...
