### ISSUE TITLE
onDrag, onTouch callback

### ISSUE THREAD

**Issue by ohlr** [express-labs/pure-react-carousel#258]
Slider should provide callbacks when being dragged or touched.
Or maybe even better a onSlideChanged callback that is triggered by any user input.

Currently only the buttons provide callbacks.

**Comment by ohlr** [comment]
keeping this open

**Comment by hyochan** [comment]
I was going to ask the same question!

**Comment by ohlr** [comment]
Are these duplicate? https://github.com/express-labs/pure-react-carousel/issues/220

**Comment by ohlr** [comment]
...

**Comment by HoereeBauke** [comment]
Any update on this???

**Comment by sebass** [comment]
not a bad question at all.. please respond

**Comment by tim-steele** [comment]
This has been answered: https://github.com/express-labs/pure-react-carousel/issues/227
