### ISSUE TITLE
use material-ui button instead of ButtonNext

### ISSUE THREAD

**Issue by shahalihridoy** [express-labs/pure-react-carousel#261]
Hello Sir,
Thanks for your great effort on this carousel which really helps to customize with reduced unpack size. I am trying to use Material-UI buttons instead of ButtonNext. Could you help me to achieve this or where can I find the functions that slides previous or next?
I will be waiting for your reply.
Thank you

**Comment by shahalihridoy** [comment]
I need help

**Comment by assetcorp** [comment]
I think this issue should be addressed. I have the same problem.

**Comment by punnadittr** [comment]
Try this 

```
<Button component={ButtonBack}>
      Back
</Button>
```
