### ISSUE TITLE
Slider view port is not hiding slides

### ISSUE THREAD

**Issue by JayJayc** [express-labs/pure-react-carousel#277]
- `pure-react-carousel` version: ^1.27.1
- `react` version: 16.13.1
- `browser` used: Chrome 83.0.4103.61
- `node` version: v12.16.2

Using Nextjs framework: v9.4.2

### Relevant code or config:

```js
<section className={styles.sliderContainer}>
            <CarouselProvider
                totalSlides={2}
                naturalSlideWidth={100}
                naturalSlideHeight={75}
                // className={styles.carousel}
            >
                {/* <Slider className={styles.slider}> */}
                <Slider>
                    <Slide index={0}>test</Slide>
                    <Slide index={1}>test</Slide>
                </Slider>
                <DotGroup />
            </CarouselProvider>
        </section>
```

### What you did:

Used basic components from github example

### What happened:

![Capture](https://user-images.githubusercontent.com/36974254/83028371-abf78f80-a074-11ea-880a-dea7f61fd470.PNG)

The second element has the hidden tag but isn't hidden
![image](https://user-images.githubusercontent.com/36974254/83028604-009b0a80-a075-11ea-8324-566f8a348e71.png)

### Reproduction:

N/A

### Problem description:

Slides are being displayed in rows

### Suggested solution:

I don't know how to fix this

### Can you help us fix this issue by submitting a pull request?

I don't know how to fix this

**Comment by JayJayc** [comment]
NextJs uses webpack and I didn't have
` import "pure-react-carousel/dist/react-carousel.es.css";
`

**Comment by muresanandrei** [comment]
This is a broken component, style just doesn't work what a crap.
