### ISSUE TITLE
Custom Slide Intervals on a Per Slide Basis

### ISSUE THREAD

**Issue by Bracciata** [express-labs/pure-react-carousel#279]
**Describe the feature you'd like:**
I would like the ability to give the carousel a list of numbers equal to the total number of slides and have it transition with the respective time waited.

**Suggested implementation:**

**Describe alternatives you've considered:**
We tried and considering implementing our own transition script but it left issues when there was interaction.

**Teachability, Documentation, Adoption, Migration Strategy:**
It would be optionally a list. We would check if an interval is a single number and if so follow same logic. However, if it is a list the size of total slides then use that for a varying interval.

**Comment by Bracciata** [comment]
I have put a pull request to add this feature https://github.com/express-labs/pure-react-carousel/pull/281

**Comment by Bracciata** [comment]
Pinging to avoid being removed due to being stale

**Comment by Bracciata** [comment]
Bump

**Comment by tim-steele** [comment]
@Bracciata I left some questions on your PR.
