### ISSUE TITLE
TypeError: this.context.subscribe is not a function

### ISSUE THREAD

**Issue by tuerkasten** [express-labs/pure-react-carousel#282]
I am facing this error just by opening my app in a Browser. Heavy assumptions where this one could possibly come from points to that oldschool react-version we are using on this project. But as far I am aware, pure-react-carousel should be working with react version 15.x || 16.x, is this right? Or is it just doomed to fail with react 16.2 ?

Anyway, I am not quite sure where to dig into myself so I just wanted to ask here.

Fun fact, it doesn't matter whether or not I am using `WithStore()`, the error goes the same.

Anything that puts me into the right direction will be warmly appreciated.

- `pure-react-carousel` version: 1.27.1
- `react` version: 16.2
- `typescript` version used: 2.9.2
- `browser` used: Chrome/83.0.4103.97
- `node` version: 12.16.1

### Relevant code or config:

class HomeContent.tsx - within `render()` method:

```js
<Segment padded="very">
    <CarouselProvider
        naturalSlideWidth={175}
        naturalSlideHeight={125}
        totalSlides={topClubs.length}
        visibleSlides={5}
        step={1}>
            <Slider>
                {topClubs.map((club, index) => (
                    <Slide index={index} key={index}>
                        <Card>
                            <Image src={club.logo} size="medium" />
                            <Card.Content>
                                <Card.Header as="h3">{club.name}</Card.Header>
                                <Card.Meta>{club.region}</Card.Meta>
                            </Card.Content>
                        </Card>
                    </Slide>
                ))}
            </Slider>
            <Button as={ButtonBack} content="Back" />
            <Button as={ButtonNext} content="Next" />
    </CarouselProvider>
</Segment>

....

// doesn't matter whether or not I'll export HomeContent with HOC, the error remains the same.
// (when using HOC, I put the provider one level above this component)
export default WithStore(HomeContent, (state) => ({ currentSlide: state.currentSlide )});
```

### What you did:
Just opened the website in Chrome. No interaction, no nothing else.

### What happened:

**Screenshot from Browser:**
![Screenshot 2020-06-13 at 12 49 00](https://user-images.githubusercontent.com/26025023/84571503-d09d7800-ad93-11ea-9a8a-05ea317a548f.png)

**Output in develpment console:**
![Screenshot 2020-06-13 at 16 39 30](https://user-images.githubusercontent.com/26025023/84571596-79e46e00-ad94-11ea-96c7-044c7309afff.png)

### Can you help us fix this issue by submitting a pull request?
probably

Cheers

**Comment by WoodyWoodsta** [comment]
Huh? Stale after 10 days?

I'm having this issue as well.

**Comment by tim-steele** [comment]
@WoodyWoodsta can you provide more information? It appears the original user is no longer a member.

What is the file/line that is causing the error? The stack trace isn't showing Pure React carousel.

**Comment by WoodyWoodsta** [comment]
Unfortunately I've long since gone with a different solution, and so I don't have any more details for you. The above stack trace probably does show Pure React Carousel, just that it's minified.
