### ISSUE TITLE
Ability to initiate zoom functionality onClick rather than onMouseOver / onMouseOut

### ISSUE THREAD

**Issue by lukewhitmore** [express-labs/pure-react-carousel#285]
**Describe the feature you'd like:**

Thanks for a great library. Our team is currently using this to provide a themed gallery feature for our site.

One of the requirements is to provide a zoom based on the user clicking on the main image.

- We've made use of the `<ImageWithZoom>` component to provide this.
- The zoom is currently initiated via an onMouseOver event handler.
- Our use-case requires the zoom to be initiated via an onClick handler.

In order to make this change, we thought we would be able to make use of the 'event props' feature provided by pure-react-carousel. 

However, as we understand it, this will only allow us to add a new callback to the stack - rather than replace the default onMouseOver hander that's currently in use.

If there isn't currently a way to achieve our aim, perhaps this functionality could be useful as a feature enhancement?

**Comment by tim-steele** [comment]
@lukewhitmore it sounds like you could use the regular `<Image>` component and right zoom logic for a click event?
