### ISSUE TITLE
Next Last Buttons Positioning

### ISSUE THREAD

**Issue by maxwell-oroark** [express-labs/pure-react-carousel#29]
I'm looking for a way to get my chevron arrows vertically aligned in the middle of the slide y-axis and be on opposite sides of the slides and having trouble. 

Do you have insight into how I would do this?

<=     [slide 1] [slide2] [slide3]  =>

**Comment by mrbinky3000** [comment]
Basically, wrap your Slider and button components in a DIV that has relative positioning, then absolute position the buttons. I'm creating an example for you.  It will be in the next release, or you can look at this file...

https://github.com/express-labs/pure-react-carousel/tree/patch/moar-docs/src/App/examples/Example6

Eventually this URL will go away once the PR is merged back into master and published.

**Comment by mrbinky3000** [comment]
Here is the new home of that example for you...
https://github.com/express-labs/pure-react-carousel/tree/master/src/App/examples/Example6
