### ISSUE TITLE
Lock outer overflows on slider swipe

### ISSUE THREAD

**Issue by niconiahi** [express-labs/pure-react-carousel#295]
**Describe the feature you'd like:**
Right now when swiping on my mobile, I can at the same time be swiping and scroll the browser up and down. What I would like (if possible) is a way of configuring it so I can specify if that should or not happen

**Suggested implementation:**

I would like if the library expose a prop somewhere (kind of similar to `lockOnWindowScroll`) which could be called `lockOverflowsOnSwipe` (or something like that)

**Describe alternatives you've considered:**

I have considered no alternatives

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tim-steele** [comment]
Is this similar to https://github.com/express-labs/pure-react-carousel/issues/294?
