### ISSUE TITLE
Stop automatically closing issues

### ISSUE THREAD

**Issue by cjayross** [express-labs/pure-react-carousel#300]
The stale bot is way too eager to close issues when, in honesty, 15 days is way too short of a timespan to consider an issue stale at all. As a result of this, issues that may be regarding honest considerations are being suppressed unnecessarily.

**Comment by tim-steele** [comment]
@cjayross what would you recommend is a good time period for stale bot?

**Comment by cjayross** [comment]
In my opinion the root of the problem is just the closing of stale issues. I think its fine to simply label them as stale, even with the time currently being used.

**Comment by tim-steele** [comment]
2020 has been a bit of a bumpy year for everyone. Unfortunately, we have not been as responsive as we have in the past to opened issues. It is something we need to work on. To me, addressing issues, and adding the correct labels will enable us to keep issues open without being flagged or marked by Stalebot.

I am not sure it makes sense to keep issues open indefinitely. There are a number of issues opened against this project that are not true issues. We have provided help via issue templates or links to the carousel's StackOverflow section. We still however get requests for personal help or questions that are in the documentation. We understand there is not a "forum" section on GitHub so people tend to open an Issue for help, but all contributors are very busy. As much as we would like to help everyone we just simply don't have the time. We want to make sure that issues being opened are true issues and or discussions around the carousel.

I do think we can increase the time something gets marked as stale to 14 days, and increase the time it is closed to 14 days of being stale. This gives 4 weeks for an open issue. We should be reviewing open issues within the initial 2 weeks, and properly responding or applying labels. I think this will solve the root of the problem.
