### ISSUE TITLE
Lazy loading example?

### ISSUE THREAD

**Issue by rscotten** [express-labs/pure-react-carousel#301]
Hello, is there a canonical lazy loading example?  

The Slick library has "ondemand" and "progressive" options for lazy loading slides, which work really well.

I can't find anything in the pure-react-carousel docs discussing how to lazy load.  Is it a feature?  If not, can it be added?

**Comment by mrbinky3000** [comment]
PRC tries to be bare bones.  If you want to lazy load your carousel content there are plenty of ways to hook into the inner-workings of the carousel and add whatever lazy load mechanism you desire.

In PRC, the "currentSlide" is the leftmost visible slide.  You also have a value for "visibleSlides" which tracks how many carousel elements you show at a time.  Both of those values are stored in the carousel's context.  You can create a higher order component to pass these values to your slide content.  Your slide content can then determine if it wants to lazy load or not.

To find out how to compute if the current slide is visible, look at our code here:  https://github.com/express-labs/pure-react-carousel/blob/d7dd7388b7570b6aab6ba0bbbed39475f17eb033/src/Slide/Slide.jsx#L56

So, yes, this is possible.  It's not available out-of-the-box nor will it ever be.  It's not the goal of PRC to encapsulate other functionality outside of being a carousel.

**Comment by bcarroll22** [comment]
Closing, since this isn't an issue. @rscotten feel free to open an RFC or draft PR if you'd like to see something like this added and find a way to do it that doesn't overstep the responsibility set of PRC.

Good luck!

**Comment by rscotten** [comment]
@mrbinky3000 @bcarroll22 Thanks for the quick responses and clarification.

That's a bummer lazy-loading is beyond the scope of this package.  The biggest issue I have with carousels is them loading all images at once and slowing down the page load.

If it's beyond the functional scope, it still would be super helpful if there was at least a canonical lazy loading example provided to show us how to implement.  I'll do my best to figure it out, though.

Thanks again.

**Comment by mehranabi** [comment]
Hey everyone,
Thanks for this great package!

I was looking for Lazy Loading options and I saw @mrbinky3000's helpful message, and I came up with this code here, which is working as far as I see:
```
class MySlider extends React.Component {
    render() {
        const { images, currentSlide } = this.props

        return (
            <Slider>
                {images.map((s, i) => (
                    <LazySlide
                        key={i}
                        index={i}
                        src={s}
                        current={currentSlide}
                    />
                ))}
            </Slider>
        )
    }
}

const MyLazySlider = WithStore(MySlider, (state) => ({
    currentSlide: state.currentSlide,
}))
```
```
const LazySlide = ({ index, src, current }) => {
    const wasVisible = useRef(false)
    const isVisible = current === index // I have only one visible slide at once

    if (!wasVisible && isVisible) {
        wasVisible.current = true
    }

    return (
        <Slide index={index}>
            {wasVisible.current && (
                <Image
                    src={src}
                    style={{
                        width: '100%',
                        height: 250,
                        objectFit: 'cover',
                    }}
                />
            )}
        </Slide>
    )
}
```

That would be great if you guys give me some feedback if you got some time! and maybe add it as an example. Thank you.
