### ISSUE TITLE
Slide continuously forward

### ISSUE THREAD

**Issue by rodelrebucas** [express-labs/pure-react-carousel#302]
Hi, is it possible to slide forward continuously without sliding back to the first index?

E.g. If I have items 1, 2, 3. I want it to slide forward like: 1, 2, 3, 1, 2, 3.... continuously.

**Comment by tim-steele** [comment]
We have infinite scroll, it goes back to the first. People have asked for infinite scroll feature and functionality without scrolling back to the first - and we would welcome a pull request for this feature.

However this is not an issue, so I am closing this. If you would like to open a feature request for a PR for this feature we would be open to a PR.
