### ISSUE TITLE
TypeError after updating to Webpack 5.1.1

### ISSUE THREAD

**Issue by arturhenryy** [express-labs/pure-react-carousel#307]
After updating to newest webpack 5.1.1 i get the following error:

error - ../node_modules/pure-react-carousel/dist/react-carousel.es.css
TypeError: Cannot read property 'tapAsync' of undefined

- `pure-react-carousel` version:
1.27.5

**Comment by tim-steele** [comment]
Hello @arturhenryy - can you re-open this issue using the bug template, please?
