### ISSUE TITLE
How to not stop isPlaying (autoplay) when ButtonBack or ButtonNext is clicked?

### ISSUE THREAD

**Issue by michgrenda** [express-labs/pure-react-carousel#314]
It's strange, one of the examples (Horizontal Carousel Auto Play) works correctly. However, the copied example doesn't work. I have noticed that if I click ButtonNext, ButtonBack, or Dots, ButtonPlay changes "state" and displays corresponding text. I'm using TypeScript. 

"dependencies": {
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/bootstrap": "^5.0.0",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.19.3",
    "@types/node-sass": "^4.11.1",
    "@types/react": "^16.9.55",
    "@types/react-dom": "^16.9.9",
    "@types/react-router-dom": "^5.1.6",
    "bootstrap": "^4.5.3",
    "focus-visible": "^5.2.0",
    "node-sass": "^5.0.0",
    "pure-react-carousel": "^1.27.6",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.0",
    "typescript": "^4.0.5",
    "web-vitals": "^0.2.4"
  }

**Comment by tim-steele** [comment]
If this is a bug you are reporting, can you please re-open using the bug template?
