### ISSUE TITLE
Ability to pass in props for aria label overrides?

### ISSUE THREAD

**Issue by kylane** [express-labs/pure-react-carousel#315]
**Describe the feature you'd like:**

It would be nice to customise the aria-labels for screen readers, as terminology may need some context.

**Suggested implementation:**

Simply add an object as a prop for each of the components to override the default aria labels.

Perhaps with dynamic objects (ie. the dot group has multiple, atm its the same label for each) perhaps have some replacable strings like [totalSlides] [thisSlide] etc....

**Describe alternatives you've considered:**

Im at a stage where I may need to just fork your awesome repo to customise.

**Teachability, Documentation, Adoption, Migration Strategy:**

eg. <ButtonBack ariaOverride={{ button: 'Next slide' }} />
eg. <DotGroup ariaOverride={{ label: 'Slide [number]' }} />

**Comment by tim-steele** [comment]
Is aria-label not passed through? I can see why it wouldn't on dot group, but not on back button?
