### ISSUE TITLE
Children of Slider/Slide are not re-rendering on state change

### ISSUE THREAD

**Issue by roshcagra** [express-labs/pure-react-carousel#316]
- `pure-react-carousel` version: 1.27.6
- `react` version: 16.13.1
- `browser` used: Chrome
- `node` version: 12.16.3

### Relevant code or config:

https://codesandbox.io/s/prod-worker-qmkjy?file=/src/App.js:439-443

### What you did:

Triggered a state change from an onClick within a `Slide` and the child of the slide wasn't updating to reflect the change.

### What happened:

State changes that should force a re-render of the children of `Slider` or `Slide` are not resulting in the expected re-render. What I have discovered is that when you drag to slide or click slide buttons, the re-render is then triggered.

### Reproduction:

See the code sandbox:

1. Click on 'Slide One'; the item should become blue, as expected.
2. Click on 'Slide Two'; the item turns blue, but now the second item is blue, but the first item is no longer blue :(
3. Drag the slider around a bunch, eventually the component will re-render and both slides will be blue 

### Problem description:

State changes that affect the children of the slider should trigger a re-render.

### Suggested solution:

I've looked through `Slide` and `Slider` a bit and can't figure this out.

**Comment by tim-steele** [comment]
@roshcagra do you happen to have an example of this bug somewhere? We will look into this.

**Comment by roshcagra** [comment]
@tim-steele The code sandbox linked in the bug should give you a simple repro

**Comment by tim-steele** [comment]
@roshcagra So it doesn't look like this is a bug in that it is _never_ forcing a re-render. I am also not sure if it is a rendering bug. It looks like there is an issue with the state. I am not sure if it is a carousel issue or if there is an issue somewhere else. We would need to look at this outside of the sandbox in a React debugger. It does look like it is re-rendering though.

**Comment by cyphire** [comment]
This isn't a bug....

You are mutating the blueItems state array, but your render has a constant getting it's value.  Just because blueItems mutated, that didn't force a rerender of the slides....

` const isBlue = blueItems.includes(thing.id);
`

Here is a simplified example which has a color component to the state we actually want to force the component to rerender: slidesToShow!

Works perfectly... Because we are mutating the slidesToShow, you get what you want...

```

 const slidesToShow = [
    { id: "One", color: "white" },
    { id: "Two", color: "white" }
  ];

const Example = () => {
 
	const [mySlides, setMySlides] = React.useState(slidesToShow);

  const onClick = (index) => {
    let tempSlides = [...mySlides];
	console.log(JSON.stringify(tempSlides))

    tempSlides[index].color = (tempSlides[index].color == "white") ? "blue" : "white";
    setMySlides(tempSlides);
  };

  return (
    <CarouselProvider
      isIntrinsicHeight
      // The natural height and width are required properties but not used since isIntrinsicHeight
      // is set
      naturalSlideHeight={500}
      naturalSlideWidth={100}
      totalSlides={slidesToShow.length}
      visibleSlides={2}
    >
      <Slider>
        {slidesToShow.map((thing, idx) => {
          return (
            <Slide index={idx} key={thing.id}>
              <div
                onClick={() => onClick(idx)}
                style={{
                  backgroundColor: thing.color
                }}
              >
                {`Slide ${thing.id}`}
              </div>
            </Slide>
          );
        })}
      </Slider>
    </CarouselProvider>
  );
}
```

**Comment by tim-steele** [comment]
@allcontributors please add @cyphire for question
