### ISSUE TITLE
I have an example of a dynamic height sized carousel which is pretty nice...

### ISSUE THREAD

**Issue by cyphire** [express-labs/pure-react-carousel#317]
I like this carousel, but didn't like that I had to know the height of the component.

I read that those who used fixed height images, wouldn't have an issue with this, but I am rendering a group of carousels on one page and need to be able to show them without too much padding underneath.  These are blogs (articles).  Because some are short and some are long, there doesn't seem to be a way of doing this.

My page is a COLLECTION of carousels using this repository.  I have extracted a simpler example (it is very ugly, just quickly did enough CSS to show it off), and present it if it can help anyone.

It dynamically creates blog entries and measures them, updating the page dynamically for height and if the screen is resized, same.  It also changes the number of columns which are shown, easy for anyone to change it to their specs.

I would like to contribute to this project with this code if it would help.

(https://github.com/cyphire/pure-react-carousel-dynamic-example)

ATTENTION!!!

The source for this (much more complex) is now updated to truly work.  Please send a message if you want me to update the example for a great dynamic ref time!

**Comment by tim-steele** [comment]
Thanks @cyphire - we do welcome pull requests. Can you open it as a draft pull request? It is easier to review changes vs. looking at just the source code.
