### ISSUE TITLE
Is it possible to create a slider like partially visible on both sides?

### ISSUE THREAD

**Issue by JomolJohn** [express-labs/pure-react-carousel#320]
Hello, 

I loved you plugin, I didn't find an option to create a plugin with center-mode. I mean both the side should partially show the slide. 
You can see this in this url : https://w3js.com/react-multi-carousel

It would be great, if you implement this too.

Thank you

**Comment by tim-steele** [comment]
Hello @JomolJohn this is a feature request. Please use the feature request Issue template.

However, to save you some time before opening the request, it would probably be best if you would open a pull request with the feature you are requesting. We are open to pull requests.

**Comment by CitizenBeta** [comment]
@JomolJohn did you find a solution for this?

If not, @tim-steele can you provide some suggestions on how you would do it? I can write the code for the pull request, I'm just now sure what the recommended route would be.

**Comment by CitizenBeta** [comment]
This may be a duplicate of this: https://github.com/express-labs/pure-react-carousel/issues/242

I'll try that and see if it works.

**Comment by CitizenBeta** [comment]
For any one finding this from a search, all you need to do is add:

```
padding-left: 25%;
padding-right: 25%;
```

To the <Slider> component
