### ISSUE TITLE
swipe multiple sliders simultaneously

### ISSUE THREAD

**Issue by pascaltan** [express-labs/pure-react-carousel#321]
**Describe the feature you'd like:**

I'm currently implementing a feature with multiple synced carousels.
The problem is, that the swipe event for the other carousels only gets fired when the drag is over.

![carousel-current](https://user-images.githubusercontent.com/12095483/101644164-2a29eb00-3a35-11eb-9e0c-abc8de505a72.gif)

it would be nicer if the carousels would stay in sync while dragging (like it's implemented for the next / back button)

![carousel-wish](https://user-images.githubusercontent.com/12095483/101644372-65c4b500-3a35-11eb-937f-5ad7385920cf.gif)

**Comment by jackguoAtJogg** [comment]
@pascaltan Is this figured out? I'm running into the issue, could you share a solution if possible? :)
