### ISSUE TITLE
Breakpoints to allow different slider settings and different screenwidths

### ISSUE THREAD

**Issue by sebreens** [express-labs/pure-react-carousel#327]
It would add a lot to the slider if it would be possible to introduce breakpoints for which different settings could be passed to the carousel provider.

I am working for a project where on mobile sizes the slider should show 1 slide, whereas on desktop - 3 slides. I have implemented a workaround that sort of works - the only problem is that when the slider goes too far on the right on mobile, switching it to desktop makes the slider show only 1/2 slides depending on how far it had went.

**Comment by KeeganFargher** [comment]
Not sure if there's a better solution, but I used a `useBreakpointValue` hook like so:

`const visibleSlides = useBreakpointValue([3, 3, 4, 6]);`

and then assigned the `visibleSlides` value as well as the `key` value to force a re-render when there is a new breakpoint:

```
<CarouselProvider
        key={visibleSlides}
        naturalSlideWidth={120}
        naturalSlideHeight={155}
        visibleSlides={visibleSlides}
      >
       ...
</CarouselProvider>
```

**Comment by mrbinky3000** [comment]
You can accomplish this today using regular React.   Just off the top of my head, you could create a container around your carousel that tracks the device width and updates the props for the carousel based on device width.

This can be done today.  No need to add it to the project.

**Comment by sebreens** [comment]
> you could create a container around your carousel that tracks the device width and updates the props for the carousel based on device width.

I've done something very similar to that. My issue is that I can't access the currentSlide property on the parent. The result being that if the slider is on the right-most slide on single slide mode, then expanding the screen will result in the slider having went too far on the right. |[slide][empty][empty]| on 3 slide mode.

**Comment by TheManFromEarth1** [comment]
@sebreens Can you show your existing solution? Trying to do the same

**Comment by sebreens** [comment]
@TheManFromEarth1 Which part exactly are you interested in? I have a viewport width tracker that sets the slider settings. I just reset the current slide every time it passes to a different viewport.
