### ISSUE TITLE
Infinite mode utilizing cloned slides

### ISSUE THREAD

**Issue by tandcsurf** [express-labs/pure-react-carousel#328]
**Describe the feature you'd like:**

Additional/alternate version of infinite mode that clones slides, allowing for a center-mode carousel that (like slick or other carousels) will consistently show slides to left/right of current active slide.

**Suggested implementation:**

**Describe alternatives you've considered:**

Creating a CSS-driven implementation of center-mode has worked pretty well, but a lack of cloned slides on pure-react-carousel's infinite mode will display a lot of dead space on the left of the first slide.

**Teachability, Documentation, Adoption, Migration Strategy:**

Flipping a property like "infiniteCloned={true}" on the CarouselProvider would be ideal.

**Comment by tim-steele** [comment]
@tandcsurf would you be willing to do a pull request with this feature? If you want to do a draft pull request first we would be able to review it.

**Comment by CitizenBeta** [comment]
@tandcsurf are you aware of any way to do this that doesn't cause the carousel to re-render? Cloning slides would still run into the issue that I had here:

https://github.com/express-labs/pure-react-carousel/issues/330

**Comment by nathanharper** [comment]
Bump! I would also really like this. Any movement?

**Comment by dkadrios** [comment]
double bump!  This is final piece that's keeping me from ditching react-slick
