### ISSUE TITLE
Animation doesn't always complete

### ISSUE THREAD

**Issue by CitizenBeta** [express-labs/pure-react-carousel#331]
- `pure-react-carousel` version: 1.27.6
- `react` version: 17.0.1
- `browser` used: Ubuntu Chrome Version 87.0.4280.88 (Official Build) (64-bit)
- `node` version: v14.15.1

### Relevant code or config:
My carousel:
```
<CarouselProvider
  naturalSlideWidth={100}
  naturalSlideHeight={100}
  totalSlides={albumPhotos.length}
  isIntrinsicHeight
  currentSlide={startingSlideIndex}
>
  <PhotoSlides albumPhotos={albumPhotos} />
  <PhotoSlidesContext onSlideChange={(index: number) => { onSlideChange(index) }} />
</CarouselProvider>
```
My slides:
```
export default function PhotoSlides({ albumPhotos }: Props) {
  return (
    <Slider className={styles.CarouselSlider}>
      { albumPhotos.map((albumPhoto: Photo, index: number) => {
        return (
          <Slide index={index} key={albumPhoto.id} className={styles.CarouselSlide}>
            <PhotoSlide photo={albumPhoto} />
          </Slide>
        )
      })}
    </Slider>
  );
}
```

### What you did:

Navigate through slides.

### Problem description:

The slide animation stops midway. Clicking anywhere helps to complete the animation. Gif/video example:

![animation-incomplete](https://user-images.githubusercontent.com/595049/104234257-249f3680-5421-11eb-8f40-5d072781eae9.gif)

### Suggested solution:

I'm not sure what to do here. My only thought is maybe this has something to do with the padding, but the intermittent nature makes me think otherwise. Most of the time the animation works just fine.

**Comment by CitizenBeta** [comment]
Upon further testing I was able to narrow down the intermittent-ness and can now reproduce it reliably. In short, this only happens while Chrome inspect element is open. To reproduce:

With Chrome's Inspect open:
1. Do very slow drags and the bug will *never* happen. In 50 slides I can get 0% occurrence rate.
2. Do fast drags and I can reproduce this at 50%+ occurrence.

Without Chrome's Inspect tools open, I can't reproduce.

That all being said, maybe this is a performance issue and on lesser devices, it may be possible to have the same issue happen. My guess is that the dom changing is causing chrome to slow down a little.

**Comment by lovgrandma** [comment]
Thanks for posting this issue. Was wondering why mine wasn't centering. Can confirm this simply will not reoccur if you close chrome inspection tool. Module works fine.

**Comment by herobaby71** [comment]
I encountered the issue still in Safari, even without the inspector open. Does anyone know if there is a way to optimize this?
