### ISSUE TITLE
IE Out of stack error

### ISSUE THREAD

**Issue by Victor-Varghese** [express-labs/pure-react-carousel#335]
Basic carousel not working in IE. Everything works fine, but in IE carousel is not working, i even stripped down the code to below, still its throwing error

- `pure-react-carousel` version: 1.27.6
- `react` version: 16.13.0
- `browser` used: IE
- `node` version:

### Relevant code or config:

```
 <CarouselProvider
      visibleSlides={3}
      totalSlides={6}
      step={3}
      naturalSlideWidth={400}
      naturalSlideHeight={500}
      hasMasterSpinner
    >
      <h1>Carousel (Custom Spinner)</h1>
      <p>This uses a customized spinner.</p>
    </CarouselProvider>
```

If i comment the carousel component everything works fine

**Comment by Victor-Varghese** [comment]
![Screenshot (75)](https://user-images.githubusercontent.com/44889920/104279876-07c23c00-54d1-11eb-94ca-212c40fe7797.png)

**Comment by tim-steele** [comment]
What version of IE @Victor-Varghese ?

**Comment by Victor-Varghese** [comment]
IE11,

Can someone help.

Otherwise i will have reimplement the entire carousel again from scratch using some other lib.

**Comment by tim-steele** [comment]
What is the error appearing above? Can you post the entire console?

**Comment by manu-unter** [comment]
We have the same issue - please remove the stale label!

We'd be happy to get insights into what we can do to avoid this
