### ISSUE TITLE
Option to set firmer / absolute end stops

### ISSUE THREAD

**Issue by finnmerlett** [express-labs/pure-react-carousel#353]
I love this component, it is the first carousel component (after installing at least 4 others) that worked perfectly out of the box. However, after playing around a bit I realise that there is no end stop. You can drag the carousel past the end of the line, and though it springs back, it looks a bit messy in my implementation.

I envisage a prop `endStops` with the options `'normal'`, `'firm'` (for a small but restricted drag distance back) and `'hard'` being impossible to drag past the end or beginning slide. If the `'firm'` option is too difficult, the `'hard'` option is all I really need. (an alternative name could be `'absolute'`).

I did have a look through the docs, but couldn't see any mention of an appropriate prop anywhere - apologies If I missed it though. I feel like this wouldn't be difficult to do, but I would have no idea where to start. I don't even know how the sliding/dragging works in the first place.

**Comment by captnstarburst** [comment]
Hello @finnmerlett. Just verifying your feature suggestion to make sure I understood. How the carousel currently works when a user reaches the last item of a non-infinite carousel, the carousel does not have a boundary allowing the user to attempt to drag past the last item and you are proposing having an optional prop that would prevent dragging past the last slide correct? 

https://user-images.githubusercontent.com/14241878/112895122-b75b8300-90aa-11eb-837f-c52c6a3d2179.mov

**Comment by finnmerlett** [comment]
That is indeed exactly correct :smile:

If you wanted to add additional options, you could add a 'firm' stop, where the behaviour would be as follows: when dragged past the last slide, the carousel moves a bit but doesn't follow the cursor/touch-point exactly - instead it would have an elastic feel, modelled by a scaling function on the cursor/touch-point position. I think an arctan function would be best for this as it starts off 1:1 then smoothly slows down (see graph, where real touch position would be on the x axis, and carousel position on the y axis).

This additional option, however, is just something I thought would be cool. I don't think I need it for my usecase, but it does feel like a logical other option. Don't feel like you have to include it at all though!

![Screenshot from 2021-03-30 14-53-41](https://user-images.githubusercontent.com/49064567/113000490-c94f2b80-9167-11eb-9a4d-8e0c061db343.png)
