### ISSUE TITLE
Would it be possible to add horizontal scrolling using a Mac touchpad?

### ISSUE THREAD

**Issue by AndrewBestbier** [express-labs/pure-react-carousel#361]
**Describe the feature you'd like:**

I would love to be able to use the Mac two-finger gestures for scrolling horizontally. I thought that `touchEnabled` would allow this but that doesn't seem to be the case. 

**Suggested implementation:**

**Describe alternatives you've considered:**

None - just not having the feature.

**Teachability, Documentation, Adoption, Migration Strategy:**

I would add this functionality to the `touchEnabled` API.

**Comment by captnstarburst** [comment]
Personally, I really like this idea, but it is such a niche feature and I am not sure any user would actually use it this way. I am gonna leave this open for a moment to think about it more but as it currently stands I don't think this would make it to release. Thank you for your suggestion though!

**Comment by captnstarburst** [comment]
Thanks for the interest. I used this as an opportunity to learn more about the support for the MacBook touchbar. It is a really interesting idea but ultimately it is outside the scope of our project. Certainly, an interesting idea, and I could see a use case for this, be it a small one.
