### ISSUE TITLE
Infinite carousel can be improved by making it infinite (continuous sliding rather going back to 1st slide at the end)

### ISSUE THREAD

**Issue by MrFarhan** [express-labs/pure-react-carousel#371]
Refer to this PR https://github.com/express-labs/pure-react-carousel/pull/187 Infinite loop can be improved as currently at the end of slides it goes back to the 1st slide, how ever the intended behavior for the word Infinite could be a loop that keeps going on. similar to this carousel https://www.youtube.com/watch?v=0YMntQg-WIk

**Describe alternatives you've considered:**
Use another npm package that provides infinite carousel.

**Comment by Hagafny** [comment]
Bump. This feature has been requested so many times. Any news on this?

**Comment by SaadBazaz** [comment]
Any support for this yet?

**Comment by iDVB** [comment]
Bump. Also looking for everything this pure React carousel has to offer, save for the infinite carousel that is not continuously going in a single direction rather than a quick slide back in the opposite direction to start over.

**Comment by Hagafny** [comment]
I had to uninstall this package and go to [React Slick](https://react-slick.neostack.com/) to get. this functionality. 
Too bad I'd much rather use this package's syntax

**Comment by AndyOooh** [comment]
Same as everyone above. Unfortunately, this is a dealbreaker.
