### ISSUE TITLE
Slider OnClick is not being prevented on Carousel movement 

### ISSUE THREAD

**Issue by Conor-Hinchee** [express-labs/pure-react-carousel#373]
- `pure-react-carousel` version: 1.27.6
- `react` version: 17.0.2
- `node` version: v10.16.1

### Relevant code or config:
` <Slider>` > `handleOnClickCapture(ev)` line #286
<img width="913" alt="Screen Shot 2021-08-05 at 1 10 43 PM" src="https://user-images.githubusercontent.com/14241878/128392575-7eb75567-a85f-4afe-91f7-8ee52ca04ca3.png">

```js
const your = code => 'here';
```

### What you did:
We are attempting to prevent clicks of the carousel slider when the carousel is in movement.

### What happened:
The onClick event is still triggered on drag events

### Suggested solution:
Remove the line #293 from `<Slider />` =

**Comment by martdavidson** [comment]
Hey this is not stale.
