### ISSUE TITLE
Add image loading error handling capabilities to ImageWithZoom

### ISSUE THREAD

**Issue by carles-codony-manomano** [express-labs/pure-react-carousel#386]
**Describe the feature you'd like:**
ImageZoom adds the zoom functionality, but removes the ability to handle loading errors.
Then as users we have to choose between handling loading errors but not having zoom, or having zoom but not being able to handle loading errors.

The need to handle loading errors is still present when using the zoom functionality, to give visual feedback to the end user as to what happened.

**Suggested implementation:**

Add the renderError and onError props so they work in the same way.

**Describe alternatives you've considered:**

None that I could imagine

**Teachability, Documentation, Adoption, Migration Strategy:**

The docs don't have a props table for ImageWithZoom, so it could be added with the error handling props included, the same as the ones for Image.

**Comment by pankaj2961** [comment]
I would like to see this feature implemented. Can I pick this issue and work on it ?
