### ISSUE TITLE
As documentation says, currentSlide property will be deprecated in future version. What is the alternative for this?

### ISSUE THREAD

**Issue by vivek1458060** [express-labs/pure-react-carousel#401]
<img width="747" alt="Screenshot 2022-03-01 at 9 30 15 PM" src="https://user-images.githubusercontent.com/26858253/156203586-9cb27d0a-d62a-4388-8149-b73f47d3f4dd.png">

**Comment by dathmart** [comment]
Good question 💭 I think a more suitable name would be `initialSlide`

**Comment by thepuzzlemaster** [comment]
I also think `defaultSlide` would conform to standard React naming conventions for a value which is only used at mount.
