### ISSUE TITLE
Enable Touch Swipe on iframes 

### ISSUE THREAD

**Issue by Jaesul** [express-labs/pure-react-carousel#405]
I'm creating a carousel that is filled with iframe slides, which doesn't allow for touch swipe on top of the iframe. This feature request is for all horizontal swiping to trigger the swipe on the carousel. 

The only workaround I've found is to put a filter on top of the iframe which disables all interaction with the iframe.

**Comment by rub1e** [comment]
@Jaesul did you find a solution in the end?

Could this issue be reopened? Making e.g. a video carousel using YouTube embeds seems like a common enough use case. I wonder if someone else has had similar issues and managed to resolve them.
