### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by lilyntalmers** [express-labs/pure-react-carousel#406]
- `pure-react-carousel` version: 8.5.5
- `react` version:
- `browser` used:
- `node` version:

### What you did:

I ran a audit on LightHouse Audit

### What happened:

And it threw an error for passive scrolling event listener
![image](https://user-images.githubusercontent.com/68227401/164790964-2f5652ac-5a02-4074-93c9-7b5d27b3ecb9.png)

### Suggested solution:

Use passive listeners to improve scrolling performance

**Comment by Conor-Hinchee** [comment]
Sorry, its taken so long for me to get back to you, thank you for the issue. After auditing the event listeners I am not seeing the opportunity to change any to passive. Closing as wont fix
