### ISSUE TITLE
ReadMe improvement - left/right keydown event listener

### ISSUE THREAD

**Issue by GLosch** [express-labs/pure-react-carousel#408]
**Describe the feature you'd like:**
Hi, I just spent a decent chunk of time trying to figure out why left/right keyboard navigation wasn't working for me. Turns out all that was needed was to `focus()` the Slider component on mount. It doesn't seem to be mentioned in the documentation, and would be helpful for anyone else who might run into this same situation.

**Suggested implementation:**

Add it to the readme

**Describe alternatives you've considered:**
Spending many hours questioning my sanity (would not recommend)

**Teachability, Documentation, Adoption, Migration Strategy:**
I'd be happy to add to the documentation if the maintainers agree that it would be helpful to include it.

**Comment by Conor-Hinchee** [comment]
@GLosch thank you for feedback and I would agree that would be helpful to add to the documentation! 
You're Pull Request would be very welcomed to improve the documentation

**Comment by GLosch** [comment]
@Conor-Hinchee great! Just opened [this PR](https://github.com/express-labs/pure-react-carousel/pull/409)
