### ISSUE TITLE
Not compatible with React 18

### ISSUE THREAD

**Issue by sagarsiwach** [express-labs/pure-react-carousel#410]
Hey,

I'm using Pure React Carousel for almost 02 Years now, and it is by far the most convenient way to add carousels to a React Environment. I was upgrading my site to react 18 and found that Pure React Carousel does not support it yet. 

Can you fix this Issue?

Thanks for your help and building such a fantastic Package

Cheers!

**Comment by tonygustafsson** [comment]
I created a pull request fixing this. Let's see if it gets approved.
https://github.com/express-labs/pure-react-carousel/pull/415

**Comment by GoetzGoerisch** [comment]
#415 was merged, we just need a new version to use it downstream.

**Comment by GoetzGoerisch** [comment]
Thanks @Conor-Hinchee!

**Comment by Conor-Hinchee** [comment]
released ! https://github.com/express-labs/pure-react-carousel/releases/tag/v1.29.0
Thank you everyone for the contributions
