### ISSUE TITLE
Advance slide from outside

### ISSUE THREAD

**Issue by bradrice** [express-labs/pure-react-carousel#411]
I need to be able to advance the slide via code from outside the CarouselProvider. It looks like currentSlide is not for this and is also deprecated.
**Describe the feature you'd like:**

I have to advance the slide after audio finishes for the slide. I thought it would be a matter of just firing an event and advancing the slide but changing the index of the slide, but I don't see where to change it.

It seems to work ok if I do set the currentSlide, but I'm afraid this option is going away. Could it be retained for a purpose such as this?

**Comment by pandanoir** [comment]
:+1:

pure-react-carousel now provides only a [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html) carousel. I want a controlled carousel too.
