### ISSUE TITLE
Demo Site Down?

### ISSUE THREAD

**Issue by PudparK** [express-labs/pure-react-carousel#412]
It's stuck on "Loading Dev App..." and the console has 404 errors. Not sure if it's just me though.

**Comment by markdesign** [comment]
yup, still down.

**Comment by Conor-Hinchee** [comment]
adding some context here, When we switched from Travis-ci to GitHub actions the deployment of the example website has broken. I am currently manually deploying the example site on every new build. I am keeping this issue open to remind myself to fix this step in the build process. 

Thank you for reporting the issue @markdesign and @PudparK its a WIP

**Comment by jtwigg** [comment]
Still down!
Even a stale one would be useful.

**Comment by mrbinky3000** [comment]
It is back up.
