### ISSUE TITLE
conflict with styled-component version

### ISSUE THREAD

**Issue by jimyeongsong** [express-labs/pure-react-carousel#416]
**Describe the feature you'd like:**

**Suggested implementation:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

<img width="594" alt="image" src="https://user-images.githubusercontent.com/105621563/174233093-1fe14480-c14e-42f7-b2bf-30ffb07f2a9d.png">

Hi, 
I would use pure-react-carousel library but I have a problem with installing.
please look picture. thank you.

**Comment by Conor-Hinchee** [comment]
@jimyeongsong thanks for bringing up this issue.
I am looking at the screenshot you have attached and do not see where this is specific to our project. It looks like you have a peer dependency issue between the two packages react-lazy-hero@2.0.0 and styled-components@5.3.5. react-lazy-hero@2.0.0 is saying your need styled-components@4.x

If you believe I am mistaken, would you mind sharing your package.json file so I can look at all your dependencies and try to recreate the issue? Without that, I am not sure I can help further.

There are some recommendations I can make still :

- you could try bumping react-hero-lazy to the latest in hopes they now support styled-components@5.3.5

- You could bump styled components down to a @4.x version

- Not a proper fix but you could run the install command with the `--force` flag or the `--legacy-peer-deps` flag

- You could open an issue with react-lazy-hero requesting that project to bump their peer-dependency to support styled-co pomnents@5.x
