### ISSUE TITLE
Add TypeScript support? 

### ISSUE THREAD

**Issue by TheFullResolution** [express-labs/pure-react-carousel#42]
Would you be interested in a pull request with typings for the pure-react-carousel? I am using the carousel at work and we have our custom types created, it wouldn't be much work for me to adjust them so they can be published on NPM together with pure-react-carousel.

Of course, if you predict breaking changes in near future I would wait for them with this pull request. #44

**Comment by mrbinky3000** [comment]
Sure, send the PR!  Thanks.

**Comment by TheFullResolution** [comment]
Pull Request added

**Comment by mrbinky3000** [comment]
Hey, @TheFullResolution, pure-react-carousel was just updated to v1.10.0 can check to see that your ts update is still accurate. A new feature was added to CarouselProvider and Slider call lockOnWindowScroll.
