### ISSUE TITLE
Intermittent Slide Overlapping.

### ISSUE THREAD

**Issue by anil-stuff** [express-labs/pure-react-carousel#420]
- `pure-react-carousel` version: 1.27.6
- `react` version: 16.14.0
- `browser` used: google chrome
- `node` version: 14

### Relevant code or config:

```js
import { Image, Slide } from 'pure-react-carousel';
```

## What happened:

We have an intermittent problem with the pure react carousel slide.
first slide `li` size getting set to `5%` instead of `10%` so that the slides getting overlapped
Once refresh the page it will fix automatically.

![image](https://user-images.githubusercontent.com/95195860/189576052-e6df6afd-eca1-4f25-a602-8359cd6f9b5f.png)
![image](https://user-images.githubusercontent.com/95195860/189576158-8b01a689-b044-4bd7-9522-0cc5cceae135.png)

Please advise

**Comment by Conor-Hinchee** [comment]
@anil-stuff thanks for raising this issue, it seems like this bug might be hard to reproduce on its own. Would you be able to spin up a demo in code-sandbox for me?

**Comment by anil-stuff** [comment]
thank you so much @Conor-Hinchee 
yeah Its hard to  to reproduce  even in my local environment. If possible I will set up a  demo. 

Thanks
Anil

**Comment by Conor-Hinchee** [comment]
Closing issue as I havent been able to reproduce
