### ISSUE TITLE
Version 1.30.0 broke the required properties

### ISSUE THREAD

**Issue by LeandroDG** [express-labs/pure-react-carousel#423]
Hi there! 

These couple of properties are now required and my code is no longer compiling:
- horizontalPixelThreshold
- verticalPixelThreshold

> No overload matches this call.
>   Overload 1 of 2, '(props: CarouselProviderProps, context?: any): ReactElement<any, any> | Component<CarouselProviderProps, any, any> | null', gave the following error.
>     Type '{ children: ("" | Element | undefined)[]; naturalSlideWidth: number; naturalSlideHeight: number; totalSlides: number; step: number; visibleSlides: number; orientation: "vertical" | "horizontal" | undefined; }' is missing the following properties from type 'CarouselProviderProps': horizontalPixelThreshold, verticalPixelThreshold

Thanks

**Comment by LeandroDG** [comment]
```
 <CarouselProvider
        naturalSlideWidth={props.slideWidth}
        naturalSlideHeight={props.slideHeight}
        totalSlides={props.slideInfo.length}
        step={visibleSlides}
        visibleSlides={visibleSlides}
        orientation={props.orientation}
      >
```

Does this help?

**Comment by LeandroDG** [comment]
That's correct, it seems they are mandatory for CarouselProviderProps, there's no question mark that'd make them optional.

Thanks!

**Comment by Conor-Hinchee** [comment]
@LeandroDG would you be able to confirm if v1.30.1 fixes the issue or if I should revert the most recent change? Thank you in advance

**Comment by LeandroDG** [comment]
I'll check! Thanks :)

**Comment by LeandroDG** [comment]
It seems to be fixed now. Thanks!
