### ISSUE TITLE
Add property `href` to `SliderProps` type for support `<Slide tag="a" href="...">`

### ISSUE THREAD

**Issue by jmas** [express-labs/pure-react-carousel#449]
**Describe the feature you'd like:**

I found that I can't pass `href` as property into `Slide` component. My goal to make slide behave as normal link. I can't use `onClick` handler because it affects SEO. When I add `href` attribute I see wrong typings:

<img width="449" alt="Знімок екрана 2023-03-28 о 15 20 23" src="https://user-images.githubusercontent.com/90701/228234081-8993b3ab-3425-43c9-8860-f9257ab80bfd.png">

**Suggested implementation:**

Juse add `href` to `SlideProps`.

And thank you for your hard work on this useful component!

**Comment by leadegroot** [comment]
Have you experimented with putting an anchor inside the Slide component?
eg 
<Slide ...>
  <a href="...">
    <Image>
  </a>
</Slide>
We are using an onclick there, but I just swapped it out locally and it seemed to work for a quick check
HIH

**Comment by jmas** [comment]
@leadegroot Hi, yep, now I deal with the problem in way you proposed. Thanks for that. Also another workaround is to re-define SlideProps with `href` attribute in `.d.ts` file.
