### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by ryanlward** [express-labs/pure-react-carousel#46]
Is there any existing way to add autoplay or programmatically advance the slide?

**Comment by tim-steele** [comment]
Hello @ryanlward -

Sorry for delayed response. We have done this by storing the current slide in the state or redux store, and setting the `<CarouselProvider>` `currentSlide` property to that value. That allows you to change the current slide from an external source/programmatically.

Hope this helps.

**Comment by mrbinky3000** [comment]
@ryanlward v1.10.0 of pure-react-carousel was just released.  It exposes the WithStore() higher order component.  So now, you have two different means to create an autoplay.

1) You can either update the currentSlide property to `<CarouselProvider>` as @tim-steele suggested.

2) You can create your own play button component and wrap that with the WithStore() HOC and update the currentSlide property that way.

**Comment by mrbinky3000** [comment]
Closing for now.  I can reopen if you still have questions.

**Comment by EdDevs2503** [comment]
Hey, how i set the Carousel autoplay? which is the code?
