### ISSUE TITLE
React, babelHelpers not defined

### ISSUE THREAD

**Issue by tuntisz** [express-labs/pure-react-carousel#47]
First and foremost, thank you for your work on pure-react-carousel. It was refreshing to find it after fighting other libraries to accomplish what I wanted.

Regarding [Issue #43](https://github.com/express-labs/pure-react-carousel/issues/43), I went ahead and gave a shot at simply exposing WithStore. See [this PR](https://github.com/tuntisz/pure-react-carousel/pull/1). In doing so, I've run into a couple issues. When running `yarn dev` from master I see the following console error:

<img width="1437" alt="screenshot 2018-01-06 20 47 56" src="https://user-images.githubusercontent.com/8322238/34646393-bf29b228-f323-11e7-96f8-d824d812cca9.png">

Furthermore, after building and pulling in the commit sha in a private repo, I get ```ReferenceError: babelHelpers is not defined
./node_modules/pure-react-carousel/dist/index.es.js/_class<```

Steps to reproduce `React is not defined`:
1. Clone https://github.com/tuntisz/pure-react-carousel#tau/export-withstore
2. Run `yarn dev`
3. Note `React is not defined` in console

Steps to reproduce `babelHelpers is not defined`:
1. Add my fork of pure-react-carousel to another project: ```
// package.json
"pure-react-carousel": "git+https://git@github.com/tuntisz/pure-react-carousel#56398e84ca5f80a3e956d442644721644ce16356",```
2. Import `WithStore` from `pure-react-carousel`;
3. Run the application
4. Note `babelHelpers is not defined`

I suspect I'm just doing something wrong in the build process though I did try from master on my fork and got the same issue.

**Comment by mrbinky3000** [comment]
Can you check out v1.10.0 and see if that fixes your problem?

**Comment by tuntisz** [comment]
v1.10.0 does indeed fix both issues. I also noticed v1.10.0 ships with the change I was going to make. This is great! Thank you.
