### ISSUE TITLE
Changing animation type

### ISSUE THREAD

**Issue by RaidoS** [express-labs/pure-react-carousel#50]
Suppose, i want change slide animation type like "Fade In" or similar. Tell me plz how make with your amazing  :100:  lib?

**Comment by mrbinky3000** [comment]
I was wondering when someone would request this.  It was on my radar.  Literally the ONLY unconfigurable styles in the entire library are the css transitions.  For some reason I totally brainfarted on that one and forgot to follow my credo of not forcing developers to defeat my css styles.   

I am going to make a new optional prop where you can pass in styles in json format to handle transition type and length.

**Comment by dblodorn** [comment]
This would be awesome - looking for a drop in to replace react-slick / this would bd the ideal.

**Comment by mrbinky3000** [comment]
Well, upon further inspection.  You can override the default animation by applying a custom global class to .carousel__slider-tray

That's not the most obvious thing, so I'll add some props to the Slider component that pass an animation class directly to the "slider tray" div so you can change the animation easily.

**Comment by mrbinky3000** [comment]
Almost done.  Thought of some other stuff that I could do here right after I made the PR.

**Comment by mrbinky3000** [comment]
v1.12.1

There is now a new prop you can add to Slider called "classNameAnimation" that makes it easier to change the css3 transition. There are also additional classes you can add to the internal workings of the Slider.  Check out the readme.

There are also now props you can add to the Slide component that let you apply a custom class to visible and hidden slides more easily.  They are classNameHidden and classNameVisible. 

As always, ever component accepts a className property too.

So, with all of this, you can now add a class to Slide that, for example sets "transition: opacity 500ms"  and then you can set classNameHidden so that opacity is 0 and classNameVisible so that opacity is visible. 

If you do that, you can make the slides "fade in"

**Comment by brandonsueur** [comment]
@HanliTheron I'm looking for the same solution, do you have a solution.

**Comment by HanliTheron** [comment]
Hi @brandonsueur, unfortunately not. It was a nice to have so I didn't waste anymore time on it. I might track back if I can make some time. 

If you however figure something out, please share with us here.

**Comment by mrbinky3000** [comment]
The "fraction" of a cell part can be done with only CSS.  Express does it on our product detail pages for mobile devices.  No prop needs to be configured.  Simple CSS will do it.

The opacity trick for the last cell can be done a few ways.  It would most likely involve javascript to set opacity on any cell that isn't currently visible.

**Comment by cristianCeamatuAssist** [comment]
> v1.12.1
> 
> There is now a new prop you can add to Slider called "classNameAnimation" that makes it easier to change the css3 transition. There are also additional classes you can add to the internal workings of the Slider. Check out the readme.
> 
> There are also now props you can add to the Slide component that let you apply a custom class to visible and hidden slides more easily. They are classNameHidden and classNameVisible.
> 
> As always, ever component accepts a className property too.
> 
> So, with all of this, you can now add a class to Slide that, for example sets "transition: opacity 500ms" and then you can set classNameHidden so that opacity is 0 and classNameVisible so that opacity is visible.
> 
> If you do that, you can make the slides "fade in"

This worked for me only if I overwrite the `classNameAnimation`, so I ended up with this:
```javascript
        <Slider classNameAnimation="fade-animation">
          <Slide classNameHidden="hide" classNameVisible="show" index={0}>
            <div>
              <Image src={Slide1} alt="Illustration" />
              <p>Find the right IP for your business</p>
            </div>
          </Slide>
         </Slider>
```

and 

```css
  .fade-animation {
    transition: opacity 2500ms;
  }

  .hide {
    transition: opacity 2500ms;
    opacity: 0;
  }

  .show {
    transition: opacity 2500ms;
    opacity: 1;
  }
```

If I keep only the `classNameAnimation` it does not work, if I keep only the `.hide` and `.show` classes it does not work.
