### ISSUE TITLE
Make Slide.renderFocusRing optional?

### ISSUE THREAD

**Issue by timc13** [express-labs/pure-react-carousel#56]
It really messes up my slide - causing the container things to shift slightly.  I even tried
```
.carousel__slide-focus-ring {
  display: none !important;
}
```
but still my slide borders are shifting slightly when i click on them.

**Comment by mrbinky3000** [comment]
Hmm.  We need the ring to be aria compliant.  Perhaps I can add an option to make the aria stuff optional, but I think this might be more of a CSS/HTML issue in your design.  Which browser are you using? Can I see the code or see it online so I can peek around in devtools?  In the meantime, here is a page that uses our carousel and the highlight ring doesn't make the slides jump around.  https://www.express.com/clothing/women/twist-strap-maxi-dress/pro/07900617/color/PITCH%20BLACK

So, it is possible to have the ring without messing stuff up.  Perhaps check out our CSS in devtools?

**Comment by TheFullResolution** [comment]
I recommend using: https://github.com/WICG/focus-visible

It fixed for us, not only carousel but also all the other buttons while keeping all aria happy 😉 

Basically, if you implement it on your page focus ring will appear on buttons only when you use a keyboard.
