### ISSUE TITLE
[Feature request] Adaptive Height & Variable Width

### ISSUE THREAD

**Issue by timc13** [express-labs/pure-react-carousel#61]
2 really great features out of the box from slick
- Adaptive Height
- Variable Width

**Comment by tim-steele** [comment]
@timc13 This is a bare bones carousel and can be responsive based on how you set it up. Please see how we are using it on express.com (i.e., https://www.express.com/clothing/men/garment-dyed-cotton-short-sleeve-shirt/pro/01702747/color/DARK%20BLUE/size/XX%20Large) and adjust your browser window to see how it is built to be fit sizes and widths.

**Comment by MrDigii** [comment]
First of all. As a full time react + typescript developer i am loving the idea of react first slider implementation. I using slick at the moment but maybe want to switch to this. For our slider implementations it is important to include slides with different heights while all slides have the same height. So different width x height ratios for each slide. Is this possible at the moment and how?

**Comment by dkadrios** [comment]
I too would love to switch from `react-slick` to this, but that lack of variable width slides is a real deal-breaker.

To be clear, we're talking about having a mix of slides with different widths at the same time, and not to be confused with having all the widths be responsive based on viewport width.  We can already do that bit using the `visibleSlides` or `naturalSlideWidth` props.  This is talking about letting each individual slide have its own width.
