### ISSUE TITLE
How can I change the selected color of <Dot/>?

### ISSUE THREAD

**Issue by JairoCardeal** [express-labs/pure-react-carousel#63]
Hi, I have two groups of <Dot/>, and I want to change the background color of selected Dots, but in diferrent colors for each group, it's possoble?

thks

**Comment by TheFullResolution** [comment]
just overwrite default styling of `.carousel__dot--selected ` and since you can pass custom classNames as a prop to `<DotGroup/>` you can style stuff as you want.

**Comment by JairoCardeal** [comment]
Hi @TheFullResolution , I already did this, but using .carousel__dot--selected, the color change in all groups, and I want different colors in each one, here is my code:

```
<CarouselProvider totalSlides={3}>     
      <div className="carousel__slide-first-group" >
        <Dot slide={0} className="carousel__slide-menu">1</Dot>
        <Dot slide={1} className="carousel__slide-menu">2</Dot>  
        <Dot slide={2} className="carousel__slide-menu">3</Dot>
      </div> 
        <Slider>
          <Slide index={0}>1</Slide>
          <Slide index={1}>2</Slide>
          <Slide index={2}>3</Slide>
        </Slider>
    <div className="carousel__slide-second-group" >
        <Dot slide={0} className="carousel__slide-dot"/>
        <Dot slide={1} className="carousel__slide-dot"/> 
        <Dot slide={2} className="carousel__slide-dot"/>
   </div>
</CarouselProvider>
```

I want both groups to have different selected colors. I not a expert in React and CSS, if you can give me some code, on how can I accomplish that, using .carousel__dot--selected, I will appreciate.

thks!

**Comment by TheFullResolution** [comment]
You can simply do:
```
.carousel__slide-first-group > .carousel__dot--selected {
  background-color: yellow;
}
.carousel__slide-second-group > .carousel__dot--selected {
  background-color: blue;
}

**Comment by JairoCardeal** [comment]
Hi @TheFullResolution , I just figured out, and work with +, the > doesn't work. 

thks a lot!
