### ISSUE TITLE
Breaks on IE11

### ISSUE THREAD

**Issue by romeboards** [express-labs/pure-react-carousel#64]
On IE11, I'm getting the following errors:

![image](https://user-images.githubusercontent.com/627751/37539226-95abb90a-2929-11e8-97db-5c89649ca57b.png)

What polyfills or shims would be necessary to prevent this issue? Thanks!

**Comment by tim-steele** [comment]
Are you seeing this in your console?

**Comment by romeboards** [comment]
Yep, thats correct. This is a printout of the stack trace from our error reporting platform.

**Comment by tim-steele** [comment]
From production?

I guess my confusion is the File "webpack://...". It looks like you are running a webpack server, which is normally what you do in local development. Are you seeing this from IE11 in local development?

**Comment by romeboards** [comment]
Yeah, the site is built on [gatsbyjs](https://www.gatsbyjs.org/), I believe that just coming from source mapping.

You can view the site where the error is geneterted here: https://www.gatsbyjs.org/

**Comment by tim-steele** [comment]
I was reviewing this. We polyfill everything in roll up when we publish the module. This looks like a webpack issue.

We use the carousel on express.com and we don't see that error in IE11 (express.com supports IE11). If you do think it is something we are doing where we aren't properly supporting IE11, `babel-preset-env` has an option where you can set target browsers (https://babeljs.io/docs/plugins/preset-env/). You can add that to the .babelrc and build it.

**Comment by TheFullResolution** [comment]
@tim-steele babel-preset-env might not be enough. Probably babel-polyfills are needed too. Only as of babel 7, they will add them automatically based on env settings. 

Anyway, we are supporting IE11 too on [greenhome.nl/energie-besparen/infraroodpanelen](https://greenhome.nl/energie-besparen/infraroodpanelen) you could see that it is a pretty complex implementation and It is working without any problems.

**Comment by romeboards** [comment]
Hi all,

Thanks for your input. I've added `babel-polyfill` to the site code as well as added the following to `.babelrc`:

```
  "presets": [
    ["env", {
      "targets": {
        "browsers": ["last 2 versions", "IE > 9"]
      }
    }]
  ]
```

However the problem continues to persist. Any thoughts on what else to try on this front? Much appreciated.

**Comment by romeboards** [comment]
Another note that the Gatsby configuration claims to support IE >= 9, the same as react: https://www.gatsbyjs.org/docs/browser-support/#specify-what-browsers-your-project-supports-using-browserslist

**Comment by tim-steele** [comment]
@romeboards I am pretty sure this is an issue with Webpack. We are not able to reproduce the issue, do not see the same issue with IE11, and @TheFullResolution is also not seeing the issue with his IE11 implementation. 

File "webpack://" leads me to believe there is an issue in the way Webpack is looking for code chunks.
