### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by ioness** [express-labs/pure-react-carousel#65]
Hello, I just wanted to share my AutoPlay solution in case someone can profit it...

class AutoPlay extends React.Component<any, any> {

  static contextTypes = {
    carouselStore: PropTypes.object.isRequired
  }

  constructor (props: any) {
    super(props)
  }

  componentDidMount () {

    const { carouselStore }: any = this.context

    setInterval(() => {
      const { currentSlide, step }: any = carouselStore.getStoreState()

      const maxSlide = this.props.totalSlides - this.props.visibleSlides
      let newCurrentSlide = Math.min(
        (currentSlide + step),
        maxSlide
      )

      carouselStore.setStoreState({
        currentSlide: newCurrentSlide === maxSlide ? 0 : newCurrentSlide
      })
    }, 2000)
  }
  render () {

    return null
  }
}

I don't know if this is the right place, thanks for reading.

**Comment by mrbinky3000** [comment]
Autoplay is now a feature in v1.12.0

**Comment by ioness** [comment]
Great, thanks
