### ISSUE TITLE
Allow setting `type=button` on DotGroup

### ISSUE THREAD

**Issue by wlingke** [express-labs/pure-react-carousel#71]
We are using this inside a form so it would be nice if we could set `type=button` so that we can keep our `type=submit` button the way it is :)

**Comment by wlingke** [comment]
I'm able to get around this by just using `Dot` instead of `DotGroup`, so I suppose this isn't an urgent issue anymore :). Up to you if you think this is worth supporting or not.

**Comment by mrbinky3000** [comment]
I think I can make this happen.  Anything to make it more configurable.
