### ISSUE TITLE
Problem loading css with webpack

### ISSUE THREAD

**Issue by alanpduque** [express-labs/pure-react-carousel#72]
Webpack gives me an error when I try to import the css file as decribed in the tutorial, even having css loaders. I think this is a matter of configuration, but I could not figure it out.

**Import line:**
`import 'pure-react-carousel/dist/react-carousel.es.css';`

**Error message:**

`ERROR in ./node_modules/pure-react-carousel/dist/react-carousel.es.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| ._buttonBack_113ph_1{cursor:pointer}
| ._buttonFirst_y31jn_1{cursor:pointer}
| ._buttonNext_p1bs6_1{cursor:pointer}
 @ ./src/components/UI/Carousel/Carousel.jsx 23:0-57
 @ ./src/components/ClientsEvaluation/ClientsEvaluation.jsx
 @ ./src/screens/Main.jsx
 @ ./src/index.jsx`

**webpack.config file:**
```javascript
{
    entry: APP_DIR + '/index.jsx',
    output: {
        path: BUILD_DIR,
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.jsx?/,
                include: APP_DIR,
                loader: 'babel-loader',
	            query: {
		            plugins: ['transform-class-properties'],
		            presets: ['stage-2']
	            }

            },
            {
                test: /\.css/,
                include: APP_DIR,
                loaders: ['style-loader', 'css-loader']
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                loader: 'url-loader?limit=100000'
            },
	        {
		        test: /\.(gif|png|jpe?g|svg)$/i,
		        use: [
			        'file-loader',
			        {
				        loader: 'image-webpack-loader',
				        options: {
					        bypassOnDebug: true,
				        },
			        },
		        ]
	        }
        ]
    },
	resolve: {
		modules: ['node_modules'],
		extensions: ['.js', '.json', '.jsx', '.css'],
		mainFields: ['loader', 'main']
	}

};
```

Any help?

**Comment by alanpduque** [comment]
A figured out the problem, it was just a matter of removing the include property of the css rule. I can't quite explain what the problem was, but I think that this property was causing webpack to ignore the css file as it was on node_modules folder.
The webpack config became as follow:

`{
    entry: APP_DIR + '/index.jsx',
    output: {
        path: BUILD_DIR,
        filename: 'bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.jsx?/,
                include: APP_DIR,
                loader: 'babel-loader',
	            query: {
		            plugins: ['transform-class-properties'],
		            presets: ['stage-2']
	            }

            },
            {
                test: /\.css/,
                **//Here is where I removed the property**
                loaders: ['style-loader', 'css-loader']
            },
            {
                test: /\.(woff|woff2|eot|ttf|otf)$/,
                loader: 'url-loader?limit=100000'
            },
	        {
		        test: /\.(gif|png|jpe?g|svg)$/i,
		        use: [
			        'file-loader',
			        {
				        loader: 'image-webpack-loader',
				        options: {
					        bypassOnDebug: true,
				        },
			        },
		        ]
	        }
        ]
    },
	resolve: {
		modules: ['node_modules'],
		extensions: ['.js', '.json', '.jsx', '.css'],
		mainFields: ['loader', 'main']
	}

};`

**Comment by jonathanwinglee** [comment]
Anyone else run into this issue? I tried the above and it did not work for me. I also tried changing the test and the loaders. I've posted in stackoverflow but never got a response.
