### ISSUE TITLE
Changing naturalSlideHeight/width resets back to the first slide

### ISSUE THREAD

**Issue by dylanpyle** [express-labs/pure-react-carousel#76]
Demo URL: https://codesandbox.io/s/qv8mo17v7j

---

Repro steps: Change the `naturalSlideHeight`/`naturalSlideWidth` prop values on `<CarouselProvider>`, after the carousel has mounted and already advanced past the first slide.

Expected result: The carousel is resized.

Actual result: The carousel resets back to the first slide.

(My use case here is that my carousel is based on the viewport size.)

**Comment by dylanpyle** [comment]
My hunch is that this line is returning `true` because `nextProps.currentSlide` is `undefined`: https://github.com/express-labs/pure-react-carousel/blob/master/src/CarouselProvider/CarouselProvider.jsx#L110 . Will confirm and open a PR if that's the case.

**Comment by tim-steele** [comment]
I merged your PR and published version 1.12.2 with the fix.
