### ISSUE TITLE
Hey, how can i have Dot active class

### ISSUE THREAD

**Issue by Lurkomorie** [express-labs/pure-react-carousel#80]
I have an active class for active dot. How can i check if dot is on right slide to give her an additioanal active class?

**Comment by Lurkomorie** [comment]
I have something like this. 
`<div className={servicesS['services-slider-dots']}>
                <Dot children={null} className={`${servicesS['services-slider-dot']} ${servicesS['active']}`} slide={0}/>
                <Dot children={null} className={servicesS['services-slider-dot']} slide={1}/>
                <Dot children={null} className={servicesS['services-slider-dot']} slide={2}/>
              </div>`

And i get: https://screenshots.firefox.com/AfDawfFemirSJMH6/localhost

but i need this: https://screenshots.firefox.com/ad4WrNxZIsA9AVB2/null

but with changing active dots

**Comment by tim-steele** [comment]
It looks like you would need to get the current slide (example in Issue #52), and then compare the index of the Dot with the current slide index, and render the active class that way.
