### ISSUE TITLE
Best way to override button behaviour on first slide

### ISSUE THREAD

**Issue by perenstrom** [express-labs/pure-react-carousel#81]
Hi

I'm loving the package, it's just what I needed for my project. But now I've hit a bit of a bump. I need to override the behaviour of the previous-button. When I am on the first slide, the previous button should not be disabled, and trigger a function changing my state (switching the slider out for a different component).

Is this possible, and what would the recommended way of doing it be?

Thanks for any help!

**Comment by tim-steele** [comment]
Hello @perenstrom the [ButtonBack](https://github.com/express-labs/pure-react-carousel#buttonback-) component has an `onClick` property and `disabled` property. It sounds like you can set the disabled to be `false` so it will never be disabled, and `onClick` to handle the click event if the current slide is 0.
