### ISSUE TITLE
Missing code from pull request

### ISSUE THREAD

**Issue by NormySan** [express-labs/pure-react-carousel#91]
Hey, I did a pull request that got merged a while ago. The following link is for the commit created after the merge.

https://github.com/express-labs/pure-react-carousel/commit/805db5de7f8143679338fc872e917f774ecbe746

It seems like some of the things added during this commit has since been removed, the things missing are the code that prevents clicks on any links in the slider while dragging as well as the dev-example of this feature and the tests.

I just wanted to make sure that this was an intended change or of this has been accidentally removed?

Best Regards,
Christoffer

**Comment by mrbinky3000** [comment]
Hey, I just diffed the master branch with the git commit you posted and the code and tests still seem to still be there.  Can you recheck. Also, can you point out which lines were removed so I know for sure what you mean.  Thanks!

**Comment by NormySan** [comment]
Hey, I've switched to another library so you can can close this issue if you want to.
