### ISSUE TITLE
Allow horizontal scrolling and customized inner slide width

### ISSUE THREAD

**Issue by anastasiaTesla** [express-labs/pure-react-carousel#93]
Hi all,
two questions also from my side.
For the horizontal carousel, is it possible to change the inner slide width, so that not exactly N (where N integer always) slides fit into the screen ( for example to show to the users better that they can also slide the carousel, e.g. showing 3.5 slides)?
I tried it this way:
```
._slideInner_fhwgk_1 {
width: 100px!important
} 
```

Also, is it possible to allow the scrolling horizontally, so that e.g. iphone users can use the momentum scrolling from iOS?

e.g. this way 
```
._horizontalSlider_al8x6_1 {
overflow-x: scroll;
-webkit-overflow-scrolling: touch;
}
```

The above pieces of code works, the problem is that they are damaging the carousel. For example, the translateX transform is not calculating correctly for each slide anymore and as a result, if I click the last slide of the carousel , the whole carousel disappears.  

Is any other recommended way to achieve the previous two things, or they are not being supported from the library at all?

Thanks in advance!

**Comment by tim-steele** [comment]
We do this using this carousel on express.com for mobile devices with more than 1 image:
![image](https://user-images.githubusercontent.com/1490225/43584063-4e52631a-962f-11e8-84df-adebe6892373.png)

Are you looking for something like this?

**Comment by tim-steele** [comment]
@anastasiaTesla I apologize, I think I wasn't clear.

On express.com, we are using the pure-react-carousel to achieve what you are asking. You can use it to do horizontal scrolling, have things centered, and halved/partially visible.

**Comment by anastasiaTesla** [comment]
Ok, nice.
Should I set some specific property/properties to specific values achieve it?
e.g. I thought regardless of the value of the naturalSlideWidth property, every-time an integer number of slides was visible. 
Also, how can I enable horizontal scrolling except of the way I wrote when opening the topic?

**Comment by tim-steele** [comment]
@anastasiaTesla The carousel was designed to be minimally opinionated. You would just need render `<Slide>` components, have them horizontally placed, and hide using overflow hidden on a surrounding container.
