### ISSUE TITLE
Right click carousel sticks to cursor?

### ISSUE THREAD

**Issue by codepressd** [express-labs/pure-react-carousel#96]
I don't know if any has seen this behavior, but when I right click -> inspect on the carousel it seems to stick to the cursor. 

I've tried to disable dragging and touch but nothing seems to stop that from happening.

Kinda wondering if anyone has seen this? If there might be a simple fix? 

Thanks,
Chris

**Comment by tim-steele** [comment]
This is an interesting bug. Open to any help looking into it.

**Comment by codepressd** [comment]
Yea look in to it

**Comment by mrbinky3000** [comment]
@codepressd I needed to fix this for our use.  I found the issue and will have a PR very soon.  Just working on the tests now.  Hint: no mouseup.

**Comment by mrbinky3000** [comment]
Should be fixed now!
