### ISSUE TITLE
Changing the way autoplay works

### ISSUE THREAD

**Issue by aneeshtigga** [express-labs/pure-react-carousel#98]
In the current build, the autoplay feature of the carousel stops autoplaying once the carousel is clicked or interacted with. Instead of that, can we make carousel stop on mouse hover and resume autoplay once mouse leaves the carousel? Need help!

**Comment by tim-steele** [comment]
@aneeshtigga I am sure this is something that can be implemented. Pull requests are welcome!

**Comment by aanich-assf** [comment]
@aneeshtigga I have this implemented in my own project atm, I'll see if I can't get around to making a PR this weekend.

**Comment by mrbinky3000** [comment]
This is something you can program yourself.  I might make a custom Component called PauseOnHover.  

I would place all the stuff I want to trigger a pause inside of this tag.  For Example...

```javascript
const Example = () => (
  <CarouselProvider
    visibleSlides={2}
    totalSlides={6}
    step={2}
    naturalSlideWidth={400}
    naturalSlideHeight={500}
    hasMasterSpinner
    currentSlide={0}
    isPlaying
  >
    <PauseOnHover> // <----------- This is what I would add
      <Slider className={s.slider}>
        <Slide index={0}>
          {/* slide content goes here */}
        </Slide>
        <Slide index={1}>
          {/* slide content goes here */}
        </Slide>
        <Slide index={2}>
          {/* slide content goes here */}
        </Slide>
        <Slide index={3}>
          {/* slide content goes here */}
        </Slide>
        <Slide index={4}>
          {/* slide content goes here */}
        </Slide>
        <Slide index={5}>
          {/* slide content goes here */}
        </Slide>
      </Slider>
    </PauseOnHover>
  </CarouselProvider>
)
```

My new PauseOnHover component would use the WithStore() higher order component to gain access to the Carousel's context.  In English, the higher order component gives you programatic access to the carousel's shared context.  I'd make the PauseOnHover component something like this...

```javascript
import React from 'react';
import { WithStore } from 'pure-react-carousel';

class PauseOnHover extends React.Component {
  constructor(props) {
    super(props);
    this.onMouseEnter = this.onMouseEnter.bind(this);
    this.onMouseLeave = this.onMouseLeave.bind(this);
  }

  onMouseEnter() {
    this.props.carouselStore.setStoreState({ isPlaying: false });
  }

  onMouseLeave() {
    this.props.carouselStore.setStoreState({ isPlaying: true });
  }

  render() {
    return (
      <div
        onMouseEnter={this.onMouseEnter}
        onMouseLeave={this.onMouseLeave}
      >
        {this.props.children}
      </div>
    )
  }
}

export default WithStore(PauseOnHover);
```

Of course, this is all just a quick sketch. You'd have to tweak stuff.

So, I don't know if this needs to be a feature.  Perhaps I can further refine this and make it part of the suite, unless you guys want to do it?

**Comment by mrbinky3000** [comment]
I think we are going to create this component.  The ability to pause is a requirement for WCAG.  So, this is on our agenda for a future update.

**Comment by mediaupstream** [comment]
Did this get implemented?

**Comment by mediaupstream** [comment]
The suggested solution above doesn't really work in the sense of a pause/resume. When you hover over autoplay is paused, but when hovering out autoplay restarts from 0 to `interval` so it's more of a pause/resetart which isn't ideal imo

**Comment by tim-steele** [comment]
@mediaupstream we would welcome a pull request if you wanted to create one, or if you have a code example that does work it could be added to the demos.
